feat: dff short story skill
deeppavlov/dream pull request #179
Opened 2022-07-01 15:07 UTC by yashkens

2022-07-01 15:09 UTC, dilyararimovna commented on annotators/rake_keywords/server.py
> +logger.info("I am ready to respond")
этот лог должжен быть после stop_words & rake инициализиации

2022-07-01 15:12 UTC, dilyararimovna commented on assistant_dists/dream/docker-compose.override.yml
> +      - CUDA_VISIBLE_DEVICES=2
0. Какой именно девайс кроме нуля задается в других файлах yml

2022-07-01 15:12 UTC, dilyararimovna commented on assistant_dists/dream/docker-compose.override.yml
> +      - CUDA_VISIBLE_DEVICES=3
0

2022-07-01 15:13 UTC, dilyararimovna commented on assistant_dists/dream/pipeline_conf.json
> +                    "timeout": 300,
подожди, это же не скилл - зачем сервисы вызываеются в пайплайне?

2022-07-01 15:13 UTC, dilyararimovna commented on assistant_dists/dream/pipeline_conf.json
> +                    "timeout": 300,
подожди, это же не скилл - зачем сервисы вызываеются в пайплайне?

2022-07-01 15:18 UTC, dilyararimovna commented on services/prompt_storygpt/server.py
> +device = 'cpu'
убрать. девайс чекается по видимости карты

2022-07-01 15:20 UTC, dilyararimovna commented on services/prompt_storygpt/server.py
> +        text = re.sub(r'\(.*?\)', '', text)  # delete everything in ()
до этой функции сделать скомпилированнй паттерн
```
pattern = re.compile(r'\(.*?\)')
```
использовать паттерн далее как
```
pattern.sub("", text)
```

Это сильно экономичнее по времени.всегда так делай

2022-07-01 15:22 UTC, dilyararimovna commented on services/prompt_storygpt/server.py
> +    logger.info(f"masked_lm exec time: {total_time:.3f}s")
логи нгазвание

2022-07-01 15:22 UTC, dilyararimovna commented on services/prompt_storygpt/test.py
> +    url = "http://0.0.0.0:8088/respond"
это твои тесты? елси нет убрать и сделать свои

2022-07-01 15:23 UTC, dilyararimovna commented on services/storygpt/README.md
> +gpu time = 0.05 sec
числа твои или нет?

2022-07-01 15:24 UTC, dilyararimovna commented on services/prompt_storygpt/Dockerfile
> +ENV PRETRAINED_MODEL_NAME_OR_PATH ${PRETRAINED_MODEL_NAME_OR_PATH}
эта переменная в этом компоненте вроде не используется? Если  `'facebook/bart-large'` это оно и есть - замени и вынеси значение в докерфайл

2022-07-01 15:25 UTC, dilyararimovna commented on services/storygpt/server.py
> +    logger.info(f"masked_lm exec time: {total_time:.3f}s")
логи

2022-07-01 15:25 UTC, dilyararimovna commented on services/storygpt/test.py
> +    url = "http://0.0.0.0:8088/respond"
не твои тесты. сделай свои

2022-07-01 15:26 UTC, dilyararimovna commented on skill_selectors/rule_based_selector/connector.py
> +            if dialog["human_utterances"][-1]["annotations"]["intent_catcher"]["tell_me_a_story"]["detected"] == 1:
надо заиспользовать уже извлеченный список интентов `intent_catcher_intents` и проверить его

2022-07-01 15:26 UTC, dilyararimovna commented on skill_selectors/rule_based_selector/connector.py
> +            asyncio.create_task(callback(task_id=payload["task_id"], response=list(set(skills_for_uttr))))
лишн строка удалить

2022-07-01 15:34 UTC, dilyararimovna commented
еще блэк кодстайл

2022-07-05 12:01 UTC, yashkens commented on services/prompt_storygpt/README.md
> +gpu time = 0.05 sec
нет!

2022-07-05 17:05 UTC, yashkens commented on services/prompt_storygpt/test.py
> +    url = "http://0.0.0.0:8088/respond"
а как сделать тесты, если не знаешь точно, что модель сгенерирует?

2022-07-05 17:06 UTC, yashkens commented on services/storygpt/README.md
> +gpu time = 0.05 sec
опять нет. их заменить на свои или вообще что-то другое там написать?

2022-07-06 14:52 UTC, dilyararimovna requested changes

2022-07-06 14:52 UTC, dilyararimovna commented on assistant_dists/dream/docker-compose.override.yml
> +        STORYGPT_KEYWORDS_SERVICE_URL: http://prompt-storygpt:8127/respond
в .env файле надо урлы прописывать, а не тут

2022-07-06 14:52 UTC, dilyararimovna commented on assistant_dists/dream/pipeline_conf.json
> +            "prompt_storygpt": {
почему они storygpt & prompt_storygpt вызываются как скиллы? они же не реплики генерируют, а используются как сервисы в short-story-skill?

2022-07-06 14:52 UTC, dilyararimovna commented on services/prompt_storygpt/README.md
> +gpu time = 0.05 sec
замени на свои) это среднее (примерное) время инференса

2022-07-06 14:52 UTC, dilyararimovna commented on services/prompt_storygpt/server.py
> +            text += " In the end,"
At the end,
"In the end" переводится как "в конце концов"

2022-07-06 14:52 UTC, dilyararimovna commented on services/prompt_storygpt/test.py
> +    url = "http://0.0.0.0:8088/respond"
см тесты dialogpt, например)

2022-07-06 14:52 UTC, dilyararimovna commented on services/storygpt/README.md
> +gpu time = 0.05 sec
заменить на свои да

2022-07-06 14:52 UTC, dilyararimovna commented on services/storygpt/test.py
> +    url = "http://0.0.0.0:8088/respond"
см dialogpt test

2022-07-06 14:52 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +        full_ctx = ctx.misc.get('agent', {}).get('dialog', {}).get('human_utterances', [])
это актуальное замечание по-прежнему

2022-07-12 09:56 UTC, dilyararimovna requested changes

2022-07-12 09:56 UTC, dilyararimovna commented on assistant_dists/dream/pipeline_conf.json
> +                    "timeout": 3,
почему не 2?

2022-07-12 09:56 UTC, dilyararimovna commented on services/prompt_storygpt/server.py
> +        device = "cuda"
переменная device для случаев cpu не определена. Попробуй, пожалуйста, еще проверить на цпу подняв компоненты. Чтобы долго, но не падало.

2022-07-12 09:56 UTC, dilyararimovna commented on services/storygpt/test.py
> +        len(sample[0]) > 0 and len(sample[0]) > 0 and sample[1] > 0.0 for sample in result
а почему у теб есть фиксированный голд резалт, но ты его не првоеряешь?

2022-07-12 09:56 UTC, dilyararimovna commented on services/prompt_storygpt/test.py
> +        len(sample[0]) > 0 and len(sample[0]) > 0 and sample[1] > 0.0 for sample in result
у тебя есть голд резалт, почему он не проверяется??

2022-07-12 09:56 UTC, dilyararimovna commented on skill_selectors/rule_based_selector/connector.py
> -            logger.info(f"Selected skills: {skills_for_uttr}")
лог верни в самый конец, пожалуйста, он нужен

2022-07-12 09:56 UTC, dilyararimovna commented on skill_selectors/rule_based_selector/connector.py
> +                nouns.extend(dialog["human_utterances"][-2]["annotations"].get("rake_keywords", []))
get("annotations", {}) во всех местах тут - нельзя, чтобы он падал нив каких ситуациях

2022-07-12 09:56 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +            resp = requests.post(STORYGPT_SERVICE_URL, json={"utterances_histories": [[final_noun]]}, timeout=2)
тут таймаут 2, в конфиге таймаут на скилл 3 секунды. Надо бы уменьшить, или не получается?

2022-07-12 09:59 UTC, yashkens commented on assistant_dists/dream/pipeline_conf.json
> +                    "timeout": 3,
за 2 не успевает

2022-07-12 10:00 UTC, yashkens commented on services/storygpt/test.py
> +        len(sample[0]) > 0 and len(sample[0]) > 0 and sample[1] > 0.0 for sample in result
сделала, как в dialogpt. но я тоже не понимаю смысла голд резалта тогда

2022-07-12 10:02 UTC, yashkens commented on skills/dff_short_story_skill/scenario/response.py
> +            resp = requests.post(STORYGPT_SERVICE_URL, json={"utterances_histories": [[final_noun]]}, timeout=2)
в реквесте точно не хватает меньше 2 секунд иногда, могу таймаут на скилл тоже 2 поставить

2022-07-19 13:14 UTC, dilyararimovna requested changes

2022-07-19 13:14 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +            return ""
нужен какой-то лоог, в чем эксепшн

2022-07-19 13:14 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +            return ""
ну жен лог эксепшна

2022-07-25 14:10 UTC, dilyararimovna requested changes

2022-07-25 14:10 UTC, dilyararimovna commented on services/storygpt/server.py
> +            top_k=20,
можно поменьше, иначе тут сложность растет сильно, будет долго сэмплить

2022-07-25 14:10 UTC, dilyararimovna commented on services/storygpt/server.py
> +            top_k=20,
5 макс

2022-07-25 14:10 UTC, dilyararimovna commented on services/storygpt/server.py
> +            top_p=0.9,
а как себя ведут два параметра top-k and top-p? выбирают те, которые обоим параметрам удовлетворяют?

2022-07-26 19:35 UTC, yashkens commented on services/prompt_storygpt/server.py
> +    encoding = tokenizer(texts, padding=True, return_tensors="pt").to(device)
да, но в нем всегда один элемент

2022-07-26 19:36 UTC, yashkens commented on skills/dff_short_story_skill/scenario/response.py
> +    return "What do you want the story to be about?"
а их куда-то в специальное место нужно сложить или можно прямо тут списком?

2022-07-27 14:27 UTC, yashkens commented on skills/dff_short_story_skill/scenario/response.py
> +            return noun
предполагается, что там вообще будет только одно слово (или словосочетание) в ответе

2022-07-27 15:01 UTC, yashkens commented on services/storygpt/server.py
> +            top_p=0.9,
сначала top-k, а потом top-p (вроде бы?)

2022-08-09 08:10 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +            return ""
нет, нужен поный лог эксепшна, почему не было овтета. Просто выводи 
except Exception  as e:
и дальше логгируй прям e в сентри и в логгер

2022-08-09 08:17 UTC, dilyararimovna commented on services/prompt_storygpt/server.py
> +    final_text = generate_part(first_text * 2, 150, 0.8, 5, first=False)
почему текст умножается на два?

2022-08-09 08:19 UTC, dilyararimovna commented on services/storygpt/README.md
> +gpu time = 1.5 sec
cpu time?

2022-08-09 08:21 UTC, dilyararimovna commented on skill_selectors/rule_based_selector/requirements.txt
> +Werkzeug<=2.0.3
что такое?

2022-08-09 08:22 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +pattern = re.compile(r"(((tell\s(me\s)*)|(one\s))*more(\sstor((y)|(ies)))*)")
ignorecase

2022-08-09 08:22 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +STORY_TYPE = os.getenv("STORY_TYPE")
default value?

2022-08-09 08:22 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +    "Please tell me, which topic would you like it to be about?",
готовые текстовые шаблоны в common

2022-08-09 08:23 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +        story_intent = utt["annotations"]["intent_catcher"]["tell_me_a_story"]["detected"]
будет ошибка, надо  все через .get()

2022-08-09 08:23 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +    if utt["text"]:
будет ошибка, надо  все через .get()

2022-08-09 08:23 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +    if utt["text"]:
будет ошибка, надо  все через .get()

2022-08-09 08:23 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +        text = utt["text"].lower().strip()
если сделать в паттерне ignorecase, то здесь не надо делать lower

2022-08-09 08:24 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +    if utt["text"]:
будет ошибка, надо  все через .get()

2022-08-09 08:25 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +            if text in utt["text"]:
а помжно эти куску реплик бота тоже обхъединить в компайлед паттерн и проверять паттерном?

2022-08-09 08:25 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +    if utt["text"]:
будет ошибка, надо  все через .get()

2022-08-09 08:25 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +            nouns.extend(utterances[-2]["annotations"].get("rake_keywords", []))
будет ошибка, надо  все через .get()

2022-08-09 08:25 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +    "Please tell me, which topic would you like it to be about?",
все в коммон

2022-08-09 08:25 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +care_pattern = re.compile(r"(don't|(do not)) (care|know)")
ignorecase

2022-08-09 08:25 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +STORYGPT_KEYWORDS_SERVICE_URL = os.getenv("STORYGPT_KEYWORDS_SERVICE_URL")
default values?

2022-08-09 08:26 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +        nouns = full_ctx[-1].get(["annotations"], {}).get(["rake_keywords"], [])
без квадратных скобок

2022-08-09 08:26 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +        nouns = full_ctx[-1].get(["annotations"], {}).get(["rake_keywords"], [])
дальше тоже

2022-08-09 08:26 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +        except Exception:
expcept exception as e и логгируй все эксепшны обязательно. не своими словами, а те5кстом эксепшна

2022-08-09 08:27 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +    last_utt = utt["text"]
уже взят текст

2022-08-09 12:44 UTC, yashkens commented on services/prompt_storygpt/server.py
> +        text += " At the end,"
да, в две части генерируется потому что

2022-08-09 12:52 UTC, yashkens commented on services/prompt_storygpt/server.py
> +    generated_texts = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
а зачем? я же только один вариант генерирую?

2022-08-09 13:20 UTC, yashkens commented on skill_selectors/rule_based_selector/requirements.txt
> +Werkzeug<=2.0.3
случайно, наверное. ну, не поменялось же ничего

2022-08-09 13:30 UTC, yashkens commented on skills/dff_short_story_skill/scenario/condition.py
> +    "Please tell me, which topic would you like it to be about?",
в смысле мне их туда положить?

2022-08-10 17:43 UTC, yashkens commented on services/prompt_storygpt/server.py
> +    encoding = tokenizer([text], padding=True, return_tensors="pt").to(device)
проверила, работает, только очень медленно

2022-08-11 11:20 UTC, dilyararimovna requested changes

2022-08-11 11:20 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +        logger.info(e)
заменить

2022-08-11 11:20 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +        logger.info(e)
заменить

2022-08-11 11:20 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +            logger.info(f"Keyword storygpt service didn't respond. Error: {e}")
заменить

2022-08-11 11:20 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +            logger.info(f"Prompt storygpt service didn't respond. Error: {e}")
заменить

2022-08-22 14:55 UTC, dilyararimovna requested changes

2022-08-22 14:55 UTC, dilyararimovna commented on assistant_dists/dream/test.yml
> +      - CUDA_VISIBLE_DEVICES=7
prompt story gpt?

2022-08-22 14:55 UTC, dilyararimovna commented on services/storygpt/Dockerfile
> +RUN python -c "from transformers import AutoModelForCausalLM; AutoModelForCausalLM.from_pretrained('${PRETRAINED_MODEL_NAME_OR_PATH}');"
вот это здесь зачем делается, если используется другая модель?
Надо либо заменить на скачивание тех, что используются на самом деле 
```
bart_model = BartForConditionalGeneration.from_pretrained("facebook/bart-large", forced_bos_token_id=0)
bart_tok = BartTokenizer.from_pretrained("facebook/bart-large")
```

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/Dockerfile
> +ENV STORYGPT_KEYWORDS_SERVICE_URL ${STORYGPT_KEYWORDS_SERVICE_URL}
сдлелай названия переменных ровно соотвествующими названиям сервисов + url. Иначе непонятно, что есть что

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +pattern = re.compile(r"(((tell\s(me\s)*)|(one\s))*more(\sstor((y)|(ies)))*)", re.IGNORECASE)
нужно говорящее название

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +prev_pattern = re.compile(f"{re_s}", re.IGNORECASE)
нужно говорящее название

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +re_s = re_s.replace("?", r"\?")
нужно говорящее название

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +re_s = "(" + ")|(".join(STORY_TOPIC_QUESTIONS) + ")"
нужно говорящее название

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +            utt.get("annotations", {}).get("intent_catcher", {}).get("tell_me_a_story", {}).get("detected", 0)
нет. надо взять функцию get_intents из common.utils и взять из нее интенты от интент кетчера. Вдруг у нас сменится название компоненты.

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +        text = utt["text"].strip()
зачем делать стрип, если идет поиск по строке дальше. стрип только края строки правит

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/condition.py
> +            if s.group(0) == text:
оч сложно. зачем так? можно же просто матч делать тогда

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +STORYGPT_KEYWORDS_SERVICE_URL = os.getenv("STORYGPT_KEYWORDS_SERVICE_URL", "http://storygpt:8126/respond")
поменять названия

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +            int_ctx.set_can_continue(ctx, actor, CAN_CONTINUE_SCENARIO)
can not continue

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +        int_ctx.set_can_continue(ctx, actor, CAN_CONTINUE_SCENARIO)
can not continue

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +        nouns = utt.get("annotations", {}).get("spacy_nounphrases", [])
get_entities from common.utils
not only named & without types
it will be better way to get nouns

2022-08-22 14:55 UTC, dilyararimovna commented on skills/dff_short_story_skill/scenario/response.py
> +        int_ctx.set_can_continue(ctx, actor, MUST_CONTINUE)
can not continue
и такое везде, где пустая строка и конф=0

2022-09-19 14:32 UTC, dilyararimovna commented on assistant_dists/dream/gpu1.yml
> +#      - CUDA_VISIBLE_DEVICES=3
uncomment

2022-09-27 13:07 UTC, dilyararimovna approved these changes

2022-09-27 13:32 UTC, dilyararimovna approved these changes

2022-09-27 13:33 UTC, merged