dialoGPT Persona
deeppavlov/dream pull request #185
Opened 2022-07-15 12:38 UTC by dmitrymailk

Добавил предтренированную модель dialoGPT на датасете PersonaChat и сервис для ранжирования предложений по косинусной близости.

2022-07-19 13:43 UTC, dilyararimovna requested changes

2022-07-19 13:43 UTC, dilyararimovna commented on README.md
> +docker-compose -f docker-compose.yml -f assistant_dists/dream_mini/docker-compose.override.yml -f assistant_dists/dream_mini/proxy.yml up --build
dev yml

2022-07-19 13:43 UTC, dilyararimovna commented on annotators/sentence_ranker/server.py
> +            sentence_model (SentenceTransformer): модель для перевода предложения в вектор. Defaults to None.
англ

2022-07-19 13:43 UTC, dilyararimovna commented on assistant_dists/dream_mini/cpu.yml
> +      CUDA_VISIBLE_DEVICES: ""
sentence ranker тоже

2022-07-19 13:43 UTC, dilyararimovna commented on assistant_dists/dream_mini/docker-compose.override.yml
> +      WAIT_HOSTS: "convers-evaluator-annotator:8004, dff-program-y-skill:8008, sentseg:8011, convers-evaluation-selector:8009, dff-intent-responder-skill:8012, intent-catcher:8014, badlisted-words:80
верни в нескольтко строк - там удобнее смотртеь, пожалуйста

2022-07-19 13:43 UTC, dilyararimovna commented on assistant_dists/dream_mini/docker-compose.override.yml
> +        GREETING_FIRST: 0
вернуть параметры на старые

2022-07-19 13:43 UTC, dilyararimovna commented on assistant_dists/dream_mini/docker-compose.override.yml
> +        PRETRAINED_MODEL_NAME_OR_PATH: 'sentence-transformers/nli-distilroberta-base-v2'
можно без кавычек

2022-07-19 13:43 UTC, dilyararimovna commented on assistant_dists/dream_mini/log
> +=> [internal] load build definition from Dockerfile 0.0s
убрать логи

2022-07-19 13:43 UTC, dilyararimovna commented on assistant_dists/dream_mini/pipeline_conf.json
> +      "timeout": 100,
верни таймауты

2022-07-19 13:43 UTC, dilyararimovna commented on services/dialogpt_persona/Dockerfile
> +# ENV N_HYPOTHESES_TO_GENERATE ${N_HYPOTHESES_TO_GENERATE}
а можно тоже несколько гипотез возвращать? хотя бы парочку

2022-07-19 13:43 UTC, dilyararimovna commented on state_formatters/dp_formatters.py
> +    logger.info(f"FORMATTER {dialog}")
убрать

2022-07-19 13:43 UTC, dilyararimovna commented on state_formatters/dp_formatters.py
> +    return [{"dialogs": [dialog], "utterances_histories": [[utt["text"] for utt in distill_dialog["utterances"]]]}]
зачем и то, и то передавать? можно только что-то одно?

2022-07-19 13:43 UTC, dilyararimovna commented on services/dialogpt_persona/server.py
> +    }
а можно еще залить код для дообучения в отделньый файл. сюда же. спасибо

2022-07-19 13:43 UTC, dilyararimovna commented on services/dialogpt_persona/server.py
> +N_HYPOTHESES_TO_GENERATE = int(os.environ.get("N_HYPOTHESES_TO_GENERATE", 1))
в докерфайле закомменчено

2022-07-19 13:43 UTC, dilyararimovna commented on services/dialogpt_persona/Dockerfile
> +RUN python -c "from transformers import AutoModelForCausalLM; AutoModelForCausalLM.from_pretrained('${PRETRAINED_MODEL_NAME_OR_PATH}');"
но ведь веса моделей не добавлены в huggingface как ты ихз планируешь выкачать?

2022-07-19 13:43 UTC, dilyararimovna commented on services/dialogpt_persona/Dockerfile
> +RUN python -c "from transformers import AutoModelForCausalLM; AutoModelForCausalLM.from_pretrained('${PRETRAINED_MODEL_NAME_OR_PATH}');"
ты их сам туда добавил что ли?)

2022-07-20 12:36 UTC, dmitrymailk commented on services/dialogpt_persona/Dockerfile
> +RUN python -c "from transformers import AutoModelForCausalLM; AutoModelForCausalLM.from_pretrained('${PRETRAINED_MODEL_NAME_OR_PATH}');"
да. https://huggingface.co/dim/dialogpt-medium-persona-chat/tree/main

2022-07-20 15:26 UTC, dmitrymailk commented on services/dialogpt_persona/Dockerfile
> +# ENV N_HYPOTHESES_TO_GENERATE ${N_HYPOTHESES_TO_GENERATE}
используется beam_search с шириной 2

2022-07-22 07:17 UTC, dilyararimovna commented on annotators/sentence_ranker/test.py
> +                                "punct_sent": "Hi. Do you like onions?"
а почему сентенс ранкер получает 1 предложение, а не пару?

2022-07-22 07:47 UTC, dilyararimovna commented on assistant_dists/dream_mini/docker-compose.override.yml
> +        PRIORITIZE_SCRIPTED_SKILLS: 1
вернуть обратно параметры

2022-07-22 07:48 UTC, dilyararimovna commented on services/dialogpt_persona/README.md
> +sudo docker-compose -f docker-compose.yml -f assistant_dists/dream_mini/docker-compose.override.yml -f assistant_dists/dream_mini/dev.yml -f assistant_dists/dream_mini/proxy.yml up --build
команды эту и дальше убрать из доки. добавить описание, что за модель, на чем файнтюнилась, сколько, какие метрики.

2022-07-22 07:48 UTC, dilyararimovna commented on services/dialogpt_persona/server.py
> +    }
датасет persona chat надо скачивать, а тне заливать к нам на гитхаб, пожалуйста.

2022-07-27 09:22 UTC, dilyararimovna requested changes

2022-07-27 09:22 UTC, dilyararimovna commented on annotators/sentence_ranker/server.py
> +        dialogs = request.json.get("dialogs", [])
сентенс ранкер должен получать на вход пары предложений. Почему у тебя приходить dialogs?
сделать новый форматтер, назови вход sentence_pairs

2022-07-27 09:22 UTC, dilyararimovna commented on annotators/sentence_ranker/server.py
> +@app.route("/response", methods=["POST"])
можно еще попросить по аналогии с другими аннотаторами, которые аннотируют и реплику человека, и гипотезы, сделать еще доп метод response_batch, который может быть использован для ранжирования гипотез в дальнейшем

2022-07-27 09:22 UTC, dilyararimovna commented on annotators/sentence_ranker/server.py
> +        dialogs = request.json.get("dialogs", [])
то, тчо ты его используешь для ранжирования пар текста контекст+персона - это твое решение. эту же модель можно использовать для ранжирования пар контекст+гипотеза, гипотеза+персона и прочее. поэтому надол как-то абстрагироваться от названий.

2022-07-27 09:22 UTC, dilyararimovna commented on annotators/sentence_ranker/test.py
> +                                "punct_sent": "Hi. Do you like onions?"
вопрос актуальен. по повоу формата входа написала в другом файле

2022-07-27 09:22 UTC, dilyararimovna commented on assistant_dists/dream_mini/pipeline_conf.json
> +    }
верни форматирование файла назад.

2022-07-27 09:22 UTC, dilyararimovna commented on services/dialogpt_persona/README.md
> +gpu time = ??? sec
заполнить

2022-07-27 09:22 UTC, dilyararimovna commented on services/dialogpt_persona/README.md
> +- epochs=1
ну тогда текста добавь и путь к файлу с треной.

2022-07-27 09:22 UTC, dilyararimovna commented on services/dialogpt_persona/README.md
> +- epochs=1
ну к коду с треной

2022-07-27 09:22 UTC, dilyararimovna commented on services/dialogpt_persona/README.md
> +- epochs=1
код трены надо положить в папку тут тоже на гитхаб.

2022-07-27 09:22 UTC, dilyararimovna commented on state_formatters/dp_formatters.py
> +
лишня пустая строка

2022-08-01 09:49 UTC, dmitrymailk commented on services/dialogpt_persona/README.md
> +- epochs=1
лежит в services/dialog_persona/train_script

2022-10-10 07:11 UTC, dilyararimovna approved these changes

2022-10-10 07:15 UTC, merged