update entity linking
deeppavlov/dream pull request #187
Opened 2022-07-24 18:41 UTC by dmitrijeuseew

Reduce memory requirements, add spell checking.

2022-07-26 09:27 UTC, dilyararimovna requested changes

2022-07-26 09:27 UTC, dilyararimovna commented on annotators/entity_detection/server.py
> +                    out = open("log.txt", "a")
а почему мы это в файл сохраняем?

2022-07-26 09:27 UTC, dilyararimovna commented on annotators/entity_linking/Dockerfile
> +COPY ./annotators/entity_linking_rus/requirements.txt /src/requirements.txt
а почему тут докерфайл в entitiy linking, а тут rus

2022-07-26 09:27 UTC, dilyararimovna commented on annotators/entity_linking/requirements.txt
> +transformers==4.6.0
почему мы используем эти библиотеки (вроде как использующие карту), но берем докерфайл базовый образ просто питоновский?

2022-07-26 12:21 UTC, dmitrijeuseew commented on annotators/entity_detection/server.py
> +                    out = open("log.txt", "a")
Это логи, я их забыл удалить

2022-07-26 12:22 UTC, dmitrijeuseew commented on annotators/entity_linking/Dockerfile
> +COPY ./annotators/entity_linking_rus/requirements.txt /src/requirements.txt
Fixed

2022-07-26 12:22 UTC, dmitrijeuseew commented on annotators/entity_linking/requirements.txt
> +transformers==4.6.0
Заменил на базовый образ, который поддерживает gpu

2022-08-02 15:35 UTC, dilyararimovna submitted a review, later dismissed

2022-08-26 11:34 UTC, dilyararimovna approved these changes

2022-08-26 11:37 UTC, dilyararimovna requested changes
ошибки в тестах

2022-09-15 15:55 UTC, closed without merging