property extraction annotator
deeppavlov/dream pull request #202
Opened 2022-09-26 18:31 UTC by dmitrijeuseew

Annotator for extraction of user attributes triplet from utterances.

2022-10-04 14:18 UTC, dilyararimovna requested changes

2022-10-04 14:18 UTC, dilyararimovna commented on assistant_dists/dream/dev.yml
> +      - 8126:8126
до 8128 включительно заняты порты.
Бери 8129 - еще свободен

2022-10-04 14:18 UTC, dilyararimovna commented on assistant_dists/dream/docker-compose.override.yml
> +          property-extraction:8126, dff-template-skill:8120"
до 8128 включительно заняты порты.
Бери 8129 - еще свободен

2022-10-04 14:18 UTC, dilyararimovna commented on assistant_dists/dream/docker-compose.override.yml
> +      - CUDA_VISIBLE_DEVICES=7
здесь 0. Не нулевой номер девайса - в гпу1 и тест ямл

2022-10-04 14:33 UTC, dilyararimovna requested changes
Надо добавить в test.yml и прочие и добавить в список тестируемых компонент в run_tests

2022-10-14 08:15 UTC, dilyararimovna commented on annotators/property_extraction/Dockerfile
> +FROM deeppavlov/base-gpu
а версию зафиксировать?

2022-10-14 08:15 UTC, dilyararimovna commented on assistant_dists/dream/test.yml
> +  property-extraction:
а ты уверен, что на 8 влезет?

2022-10-14 08:51 UTC, dmitrijeuseew commented on annotators/property_extraction/Dockerfile
> +FROM deeppavlov/base-gpu
Зафиксировал

2022-10-14 08:51 UTC, dmitrijeuseew commented on assistant_dists/dream/test.yml
> +  property-extraction:
Сделал property extraction на cpu

2022-10-17 09:08 UTC, dilyararimovna requested changes

2022-10-17 09:08 UTC, dilyararimovna commented on assistant_dists/dream/docker-compose.override.yml
> +      - CUDA_VISIBLE_DEVICES=0
и тут осталась

2022-12-14 16:50 UTC, dmitrijeuseew commented on assistant_dists/dream/pipeline_conf.json
> +                    "annotators.sentseg"
Добавил

2022-12-15 04:23 UTC, dilyararimovna commented on assistant_dists/dream/pipeline_conf.json
> +                    "protocol": "http",
таймаут

2022-12-26 09:58 UTC, dilyararimovna approved these changes

2023-02-14 13:38 UTC, dilyararimovna requested changes

2023-02-14 13:38 UTC, dilyararimovna commented on README.md
> +black --line-length=120 annotators/entity_detection - форматирование| Spacy Annotator        | 250 MB RAM               | token-wise annotations by Spacy
артефакты случайной вставки эта и две предыдущие строки

2023-02-14 13:38 UTC, dilyararimovna commented on assistant_dists/dream/docker-compose.override.yml
> -    environment:
строчку удалил случайно

2023-02-14 13:38 UTC, dilyararimovna commented on assistant_dists/dream/docker-compose.override.yml
> +        CONFIG: t5_generative_ie_lite_infer.json
а ему карта нужна? t5 вроде написано

2023-02-14 13:40 UTC, dilyararimovna requested changes

2023-02-14 13:40 UTC, dilyararimovna commented on assistant_dists/dream/docker-compose.override.yml
> +    command: flask run -h 0.0.0.0 -p 8129
сорри, порт заняли уже, возьми другой, пожалуйста.
Например 8136

2023-02-21 05:32 UTC, dilyararimovna approved these changes

2023-02-21 05:35 UTC, merged