WIP New multitask
deeppavlov/dream pull request #203
Opened 2022-09-28 18:03 UTC by dimakarp1996

2022-10-04 15:15 UTC, dilyararimovna requested changes

2022-10-04 15:15 UTC, dilyararimovna commented on skills/dff_gossip_skill/dialogflows/flows/gossip.py
> +    "Books&Literature",
а почему ты старые удаляешь? код должен быть совместим. Здесь должны быть и старые, и новые

2022-10-05 19:46 UTC, dimakarp1996 commented on skills/dff_gossip_skill/dialogflows/flows/gossip.py
> +    "Books&Literature",
ok

2022-10-05 19:46 UTC, dimakarp1996 commented on dev_requirements.txt
> +flake8
ok

2022-10-05 19:46 UTC, dimakarp1996 commented on common/utils.py
> +    elif which == "topics":
ok

2022-10-05 19:46 UTC, dimakarp1996 commented on annotators/combined_classification/combined_classifier.json
> +               "topics":{"type":"classification","options":33}
ok

2022-10-05 19:46 UTC, dimakarp1996 commented on annotators/combined_classification/README.md
> +DistilBERT Base Uncased model for 6 tasks - emotion sentiment toxic factoid midas topic classification
ok

2022-10-05 19:46 UTC, dimakarp1996 commented on annotators/combined_classification/Dockerfile
> +RUN pip install git+https://github.com/dimakarp1996/DeepPavlov.git@clean_multitask_ready
ok

2022-10-10 18:57 UTC, dimakarp1996 commented
The reasons of the inability to merge this PR were stated in the dp_dream channel on Friday, 7 October. So, instead, I have made a New PR with the 9in1 model.

2022-10-10 18:57 UTC, closed without merging