New multitask 9in1
deeppavlov/dream pull request #207
Opened 2022-10-10 18:57 UTC by dimakarp1996

2022-10-11 12:44 UTC, dilyararimovna submitted a review, later dismissed

2022-10-11 12:50 UTC, dimakarp1996 commented on common/utils.py
> +        dp_topics_probs = _labels_to_probs(dp_topics_labels, combined_classes["topics_classification"])
Это для обратной совместимости.

2022-10-11 12:51 UTC, dimakarp1996 commented on common/utils.py
> +        dp_topics_probs = _labels_to_probs(dp_topics_labels, combined_classes["topics_classification"])
А, или она не нужна, потому что такого аннотатора в дриме и не было?

2022-10-11 12:51 UTC, dimakarp1996 commented on common/utils.py
> +        dp_topics_probs = _labels_to_probs(dp_topics_labels, combined_classes["topics_classification"])
Тогда поправлю

2022-10-13 12:33 UTC, dilyararimovna commented
![image](https://user-images.githubusercontent.com/14152126/195597011-eb7664e5-82eb-446d-b6b5-b11d42eb1e0e.png)

2022-10-26 14:38 UTC, dimakarp1996 commented
> ![image](https://user-images.githubusercontent.com/14152126/195597011-eb7664e5-82eb-446d-b6b5-b11d42eb1e0e.png)

Это было всегда. Просто скилл не реагирует на эмоцию "сюрприз".

2022-11-04 10:52 UTC, dimakarp1996 commented
Англоязычный DREAM проходит все тесты.
Русскоязычный DREAM - тесты не проходятся, потому что модель выпилена из Huggingface ( https://deeppavlov.slack.com/archives/C0140E9N42Y/p1667494074190919 ), с моими изменениями не связано
Многоязычный DREAM - тесты не проходятся, потому что test_skills не находит контейнер для convers_evaluator_selector. С моими изменениями не связано, т.к билдится нормально

2022-11-08 12:49 UTC, dilyararimovna requested changes

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/Dockerfile
> +RUN pip install git+https://github.com/dimakarp1996/DeepPavlov.git@c7e4d0c5d0ed1cc898ff8eaa2898106b2699441c
почему диппавлов из твоего форка? до этого, мы это пропустили, но нет. Тепреь давай сделаем номрально - нужна ссылка на коммит в отдельной ветке в дипппавлове. А потом заменить на конкретнюу фиксированную версию диппавлова.

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/Dockerfile
> +ARG DATA_URL=http://files.deeppavlov.ai/dream_data/distil9in1/model.pth.tar
md5 файл положил рядом на шаре?

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/README.md
> +This model(with a distilbert-base-uncased backbone) takes only 2439 Mb for 9 tasks, whereas single-task models with the same backbone for every of these tasks take up almost the same memory(~2437 Mb
это точно будет выглядеть некрасиво - полотном.сделай заголовок и поинты - с помощью *

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/server.py
> +    elif postannotations:
else просто же

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/server.py
> +        # While using postannotations, we annotate only for toxic class
а чего это вдруг? мы гипотезам бота хотим тоже все аннотации назначать!!! за этим нам и нужна мультизадачность, чтобы удешевить это все

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/server.py
> +            sentences,  # cobot dialogact intents is now trained without history
блин погодите, а почему у нас вообще разные инпуты???? идея мультизадачности в том, чтобы подать один вход и пропустить его через одну сеть, а на выходе с помощью нескольких голов получить сразу несколько классификаций же. Разве нет? нужна схема модели и объяснение. иначе я не понимаю

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/server.py
> +    logger.info("Respond")
в чем смысл этого лога - убрать

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/server.py
> +    logger.exception(f"9in1 result: {answer}")
полное название компонента нормальное (аннотатора)

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/server.py
>      logger.info(f"Combined classifier exec time: {time.time() - t}")
правильное  название компонента нормальное (аннотатора)

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/server.py
> +    logger.debug(f"9in1 batch result: {answer}")
правильное название компонента нормальное (аннотатора)

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/server.py
>      logger.info(f"Combined classifier exec time: {time.time() - t}")
правильное название компонента нормальное (аннотатора)

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/test.py
> +                "midas_classification": ["open_question_opinion", "open_question_personal", "yes_no_question"],
а почему possible_answers? они не фиксированные? каждый раз разные получаются что ли?

2022-11-08 12:49 UTC, dilyararimovna commented on annotators/combined_classification/test.py
>      logging.info("SUCCESS!")
тогда логинг убери вообще

2022-11-08 12:49 UTC, dilyararimovna commented on common/utils.py
> +    "toxic_classification",
deeppavlov topics тоже мультилейбл же договаривались?

2022-11-08 12:49 UTC, dilyararimovna commented on dev_requirements.txt
> +flake8==5.0.4
ну мы его специально не фиксим, чтобы всегда быть ап ту дейт. так что убери, пожалуйста, этот фикс

2022-11-08 12:49 UTC, dilyararimovna commented on skill_selectors/rule_based_selector/connector.py
> +            is_factoid = get_factoid(user_uttr).get("is_factoid", 0.0) > FACTOID_THRESHOLD
а чего трешхолд так сильно уменьшился. это норм?

2022-11-08 12:49 UTC, dilyararimovna commented on skills/factoid_qa/server.py
> +        is_factoid_cls = factoid_conf.get("is_factoid", 0.0) > FACTOID_THRESHOLD
а почему бы не сделать в common функцию get_factoid?

2022-11-08 13:30 UTC, dimakarp1996 commented on annotators/combined_classification/Dockerfile
> +RUN pip install git+https://github.com/dimakarp1996/DeepPavlov.git@c7e4d0c5d0ed1cc898ff8eaa2898106b2699441c
То есть риски, что диппавлов может быть заблокирован, как это уже 1 раз было, в расчёт больше не принимаются? Федя согласился с таким решением именно по причине этих рисков

2022-11-08 13:32 UTC, dimakarp1996 commented on annotators/combined_classification/server.py
> +            sentences,  # cobot dialogact intents is now trained without history
1)Нет,топики и диалоговых акты теперь без истории. Об этом говорилось на созвоне, это обсуждалось с Васей и дописывалось в документ
2)Разные входы (каждый вход для своей таски) пропускаются через одну и ту же базовую модель.
На выходе идёт классификация при помощи линейного слоя, для каждой тачки своего

2022-11-08 13:37 UTC, dimakarp1996 commented on annotators/combined_classification/server.py
> +        # While using postannotations, we annotate only for toxic class
1)Аннотации не для всех тасок используются в респонс селекторе.
2)При назначении аннотаций и в постаннотаторе для всех тасок (даже тех, что не использовалось) бот не проходил тесты диалога по времени в 10 секунд. Поэтому, чтобы эти тесты проходили б, я убрал таски, которые в респонс селекторе не использовались
3)Основную часть времени на предикт(процентов 70-80) занимает не сам инфер модели, перенос тензоров с gpu на cpu. Как в рамках текущей версии ускорить этот процесс, я не знаю (по крайней мере, в рамках данной версии pytorch - было решение для одного хакатона, ускоряющее этот процесс, но оно потребует кардинального изменения кода и версий фреймворка, известны ли тебе иные решения?)

2022-11-08 13:39 UTC, dimakarp1996 commented on annotators/combined_classification/test.py
> +                "midas_classification": ["open_question_opinion", "open_question_personal", "yes_no_question"],
Они фиксированные для данных весов, но веса могут меняться.
По сути это та же проверка, что и в респонс селекторе, где тоже проверяется матч с конкретным подмножеством топиков. Смысл этой проверки - воспроизвести условия, на которых у меня фейлился test_dialog с фразой "do you like porn", не дожидаясь этого этапа и не привязываюсь к особенностям конкретных весов

2022-11-08 13:43 UTC, dimakarp1996 commented on common/utils.py
> +    "toxic_classification",
DeepPavlov topics на моей памяти всегда был single label. Коботовским таскам мультилебельность только вредидо (т.к во-первых, мультилебельных меток было всего несколько процентов, во-вторых, даже эти несколько процентов как правило выглядили как Нормальный класс;мусорный класс и учили модель по сути вместо нормальных классов оверфититься на мусорные, ухудшая её качество)

2022-11-08 13:43 UTC, dimakarp1996 commented on dev_requirements.txt
> +flake8==5.0.4
Фикс сделан по предложению Феди, ок, уберу

2022-11-08 13:44 UTC, dimakarp1996 commented on skill_selectors/rule_based_selector/connector.py
> +            is_factoid = get_factoid(user_uttr).get("is_factoid", 0.0) > FACTOID_THRESHOLD
Да, это норм. Текущая дистил модель верно предсказывает фактоидную фразу, но с вероятностью 0.55

2022-11-08 13:44 UTC, dimakarp1996 commented on skill_selectors/rule_based_selector/connector.py
> +            is_factoid = get_factoid(user_uttr).get("is_factoid", 0.0) > FACTOID_THRESHOLD
Фактоидную фразу из test_dialog

2022-11-08 13:45 UTC, dimakarp1996 commented on skills/factoid_qa/server.py
> +        is_factoid_cls = factoid_conf.get("is_factoid", 0.0) > FACTOID_THRESHOLD
См. 251 строчка, где ровно эта функция и вызывается

2022-11-08 15:01 UTC, dimakarp1996 commented on annotators/combined_classification/test.py
>      logging.info("SUCCESS!")
done in branch

2022-11-08 15:04 UTC, dimakarp1996 commented on annotators/combined_classification/server.py
> +    logger.debug(f"9in1 batch result: {answer}")
done in branch

2022-11-08 15:04 UTC, dimakarp1996 commented on annotators/combined_classification/server.py
> +    logger.exception(f"9in1 result: {answer}")
done in branch

2022-11-08 15:04 UTC, dimakarp1996 commented on annotators/combined_classification/server.py
>      logger.info(f"Combined classifier exec time: {time.time() - t}")
done in branch

2022-11-08 15:05 UTC, dimakarp1996 commented on annotators/combined_classification/server.py
> +    logger.info("Respond")
Done in branch

2022-11-08 15:05 UTC, dimakarp1996 commented on annotators/combined_classification/server.py
> +    elif postannotations:
Done in branch

2022-11-08 15:16 UTC, dilyararimovna commented on annotators/combined_classification/Dockerfile
> +RUN pip install git+https://github.com/dimakarp1996/DeepPavlov.git@c7e4d0c5d0ed1cc898ff8eaa2898106b2699441c
расскажи это куче других кмпонент, зависящих от диппавлова

2022-11-08 15:17 UTC, dilyararimovna commented on annotators/combined_classification/server.py
> +            sentences,  # cobot dialogact intents is now trained without history
2. так у тебя в итоге 8 инферов вместо 1 - это плохо

2022-11-08 15:19 UTC, dimakarp1996 commented on annotators/combined_classification/Dockerfile
> +RUN pip install git+https://github.com/dimakarp1996/DeepPavlov.git@c7e4d0c5d0ed1cc898ff8eaa2898106b2699441c
Done in branch, но все равно призываю принимать в расчет эти риски

2022-11-08 18:07 UTC, dimakarp1996 commented on annotators/combined_classification/README.md
> +This model(with a distilbert-base-uncased backbone) takes only 2439 Mb for 9 tasks, whereas single-task models with the same backbone for every of these tasks take up almost the same memory(~2437 Mb
сделано

2022-11-09 10:34 UTC, dimakarp1996 commented on annotators/combined_classification/Dockerfile
> +ARG DATA_URL=http://files.deeppavlov.ai/dream_data/distil9in1/model.pth.tar
Добавил использование архива. Но заметим, что это уменьшает вес весов лишь на 80 мегабайт из 803. При том, что качается еще как минимум торч весом 831 Мб, а архив требует времени на разархивирование, на время билда это все равно практически не влияет. Если не в большую сторону.

2022-11-21 13:53 UTC, dilyararimovna requested changes

2022-11-21 13:53 UTC, dilyararimovna commented on annotators/combined_classification/Dockerfile
> +RUN pip install git+https://github.com/deepmipt/DeepPavlov.git@a53c42062e4bccf6ec63021ec6bd7b9fbe23f091
deeppavlov/DeepPavlov
ну как бы без разницы, но мы перешли на новый вариант уже в либе

2022-11-21 13:53 UTC, dilyararimovna commented on annotators/combined_classification/Dockerfile
> +RUN python -m deeppavlov download $CONFIG
тогда надо ~/.deeppavlov в volumes добавить 
https://github.com/deeppavlov/dream/blob/main/assistant_dists/dream/dev.yml#L268

2022-11-21 13:53 UTC, dilyararimovna commented on annotators/combined_classification/combined_classifier.json
> +        "url": "http://files.deeppavlov.ai/dream_data/distil9in1/9in1.tar.gz",
версионирования нет. файл без _vX. в названии

2022-11-21 13:53 UTC, dilyararimovna commented on annotators/combined_classification/combined_classifier.json
> +      "SINGLE_SENTENCE_LEN": 32,
оч коротко, конечно.

2022-11-21 13:53 UTC, dilyararimovna commented on annotators/combined_classification/combined_classifier.json
> +      "MULTI_SENTENCE_LEN": 64
с историей тоже очень коротко

2022-11-21 13:53 UTC, dilyararimovna commented on annotators/combined_classification/test.py
> +        {"sentences": ["movies"], "task": "deeppavlov_topics", "answers_bert": [["Movies_TV"]]},
можно посложнее примеры, пожалуйста.

2022-11-21 13:53 UTC, dilyararimovna commented on annotators/sentseg_ru/requirements.txt
> +cryptography==2.8
в чем прикол кучи таких правок, если они не настоящие? может ты не merge делаешь?

2022-11-21 13:53 UTC, dilyararimovna commented on common/utils.py
> +        "Science_and_Technology",
а почему так по-разному выглядят названия классов? везде через &

2022-11-21 13:53 UTC, dilyararimovna commented on common/utils.py
> -        cobot_topics_probs = _labels_to_probs(cobot_topics_labels, combined_classes.get("cobot_topics", {}))
?

2022-11-21 13:53 UTC, dilyararimovna commented on skill_selectors/rule_based_selector/connector.py
> +            is_factoid = get_factoid(user_uttr).get("is_factoid", 0.0) > FACTOID_THRESHOLD
так я говорю, сделай определние класса по threshold внутри get_factoid, там же используй внутри FACTOID_THRESHOLD.
А тут уже используй get_factoid proba=False, чтобы класс возвращать

2022-11-21 13:53 UTC, dilyararimovna commented on skills/dff_wiki_skill/requirements.txt
> +importlib_metadata<5
это не нужно в каждом скилле добавлять - эту зависимость уже добавили просто в зависимости dff

2022-11-21 14:37 UTC, dimakarp1996 commented on annotators/combined_classification/combined_classifier.json
> +      "MULTI_SENTENCE_LEN": 64
Это тот же размер, что и есть в текущем деве. Он был выбран, т.к покрывал основную долю уттерансов, в районе 99%

2022-11-21 14:38 UTC, dimakarp1996 commented on common/utils.py
> +            logger.warning(f"Not found Model name {model_name} in combined annotations {combined_annotations}")
Для того, чтобы иметь возможность делать запросы постаннотатору только для части моделей, ускоряя тем самым инференс

2022-11-21 15:08 UTC, dimakarp1996 commented on annotators/combined_classification/combined_classifier.json
> +        "url": "http://files.deeppavlov.ai/dream_data/distil9in1/9in1.tar.gz",
Передал просьбу Феде, у меня нет права на шаре переименовать этот файл

2022-11-21 15:15 UTC, dimakarp1996 commented on common/utils.py
> -        cobot_topics_probs = _labels_to_probs(cobot_topics_labels, combined_classes.get("cobot_topics", {}))
Это же действие выполняется ниже, строчка "    if not cobot_topics_probs: "

2022-11-21 15:22 UTC, dimakarp1996 commented on common/utils.py
> +        "Science_and_Technology",
Выглядят в соответствии с предоставленным мне списком. Могу поправить

2022-11-21 18:02 UTC, dimakarp1996 commented on annotators/combined_classification/Dockerfile
> +RUN pip install git+https://github.com/deepmipt/DeepPavlov.git@a53c42062e4bccf6ec63021ec6bd7b9fbe23f091
Добавлю, что единственная фраза, которая проверяется подобным образом, проверяется также более строгим образом на других проверках.

2022-11-21 18:05 UTC, dimakarp1996 commented on annotators/combined_classification/Dockerfile
> +RUN python -m deeppavlov download $CONFIG
Если его туда добавить и оставить директорию модели такой, как была на момент комментария, то тогда в соответствующей директории веса модели не находятся. В связи с этим я вернул старую директорию для загрузки - /tmp , как и была. Из volumes тогда нужно убрать ~/.deeppavlov ?

2022-11-21 18:05 UTC, dimakarp1996 commented on annotators/combined_classification/combined_classifier.json
> +        "url": "http://files.deeppavlov.ai/dream_data/distil9in1/9in1.tar.gz",
переименовал

2022-11-21 18:07 UTC, dimakarp1996 commented on annotators/combined_classification/test.py
> +        {"sentences": ["movies"], "task": "deeppavlov_topics", "answers_bert": [["Movies_TV"]]},
Добавил примеры посложнее. Также в тесты для deeppavlov_topics интегрированы 2 примера, на которых этот аннотатор косячит. Заметим, что как минимум из-за первого из этих 2 примеров заменить cobot_topics данным классификатором нельзя, иначе бот не будет проходить тесты на соответствующей фразе.

2022-11-21 18:07 UTC, dimakarp1996 commented on annotators/sentseg_ru/requirements.txt
> +cryptography==2.8
fixed

2023-01-17 04:28 UTC, dilyararimovna commented
Closed because of the #213 PR (the model results are better in #213)

2023-01-17 04:28 UTC, closed without merging