New multitask 9in1 (Singlelabel version)
deeppavlov/dream pull request #213
Opened 2022-11-15 15:56 UTC by dimakarp1996

Last singlelabel version of multitask distilbert. Added on Vasily request. PR is interchangeable with https://github.com/deeppavlov/dream/pull/207 , will be merged there if passes the tests

2022-12-05 02:51 UTC, dilyararimovna requested changes
замени еще в dream_sfc - там же тоже combined используется.

2022-12-05 02:51 UTC, dilyararimovna commented on skills/emotion_skill/data/data.json
> +         "I see that you are in disgust. I am sorry. Maybe we should talk about movies instead?"
мне кажется, не надо так говорить. Замени на что-нибудь, я вижу, что тебе не нравится тема, может предложишь тему для разговора

2022-12-05 02:51 UTC, dilyararimovna commented on skills/factoid_qa/requirements.txt
> +importlib-metadata<5.0
почему тут куча файлов с изменениями, которых нет? можешь подмержить свежий дев, пожалуйста

2022-12-05 09:29 UTC, dimakarp1996 commented on skills/factoid_qa/requirements.txt
> +importlib-metadata<5.0
подмержил, убрал все такие изменения

2022-12-05 09:29 UTC, dimakarp1996 commented on skills/emotion_skill/data/data.json
> +         "I see that you are in disgust. I am sorry. Maybe we should talk about movies instead?"
заменил на нечто аналогичное. в dream_sfc тоже заменил

2022-12-13 08:41 UTC, dilyararimovna commented on common/utils.py
> +        "Science_and_Technology",
у нас нет такого класса в дп топикс, он называется по-другому. ТО же самое про movies_tv - у нас по-другому называется. Почему тут так называются классы? ты соединял датасеты дп топикс. счем-то при обучении или нет?

2022-12-13 09:03 UTC, dimakarp1996 commented on common/utils.py
> +        "Science_and_Technology",
Я ничего не соединял. Просто переименовал классы. Это переименование нужно, чтобы DREAM без дополнительных усилий со стороны разработчика скиллов понимал, что Movies TV от cobot topics и от deeppavlov topics - один и тот же класс, и чтобы ему не нужно было везде прописывать 2 однотипных класса

2022-12-20 10:34 UTC, dilyararimovna requested changes

2022-12-20 10:34 UTC, dilyararimovna commented on annotators/combined_classification/Dockerfile
> +RUN pip install -r requirements.txt
я же тебе скидывала от Феди замечания по пулл-реквесту. Почему ты делаешь наоборот?)
Сначала установка ВСЕХ зависимостей, а потом уже копирование файлов

2022-12-20 10:34 UTC, dilyararimovna commented on annotators/combined_classification/test.py
> +            "answers_bert": [["toxic"], ["not_toxic"]],
2 примера, 3 ответа

2022-12-20 10:34 UTC, dilyararimovna commented on annotators/combined_classification/test.py
> +            "answers_bert": [["toxic"], ["not_toxic"]],
но тесты проходят. Есть вопросы к тестам. Проверь заново саму проверк, что там все корректно

2022-12-20 10:34 UTC, dilyararimovna commented on common/utils.py
> +topic_groups = {
все эти вещи - это контанты. Константы пишут заглавными буквами. Поправь везде

2022-12-20 10:34 UTC, dilyararimovna commented on assistant_dists/dream/dev.yml
> +      - "~/.deeppavlov:/root/.deeppavlov"
в dream_alexa еще новый дистр добавь это, пожалуйста.
Кстати если используются веса только из диппавлова, то можно строку выше убрать

2022-12-20 12:38 UTC, dimakarp1996 commented on annotators/combined_classification/Dockerfile
> +RUN pip install -r requirements.txt
Я так и делаю. Внимательно посмотри на код. 
https://github.com/dimakarp1996/dream/blob/new_multitask_9in1_singlelabel/annotators/combined_classification/Dockerfile
16-17 строчки - установка всех зависимостей. 19-20 строчки - копирование файлов.

2022-12-20 12:45 UTC, dimakarp1996 commented on assistant_dists/dream/dev.yml
> +      - "~/.deeppavlov:/root/.deeppavlov"
Веса не только из диппавлова

2022-12-20 13:07 UTC, dimakarp1996 commented on assistant_dists/dream/dev.yml
> +      - "~/.deeppavlov:/root/.deeppavlov"
добавил

2022-12-21 02:18 UTC, dilyararimovna requested changes

2022-12-21 02:18 UTC, dilyararimovna commented on annotators/combined_classification/Dockerfile
> +RUN pip install -r requirements.txt
посмотри еще раз

2022-12-21 02:18 UTC, dilyararimovna commented on annotators/combined_classification/Dockerfile
> +RUN pip install -r requirements.txt
22 строка - установка зависимостей

2022-12-21 02:18 UTC, dilyararimovna commented on assistant_dists/dream/dev.yml
> +      - "~/.deeppavlov:/root/.deeppavlov"
не добавил же? dream_alexa дистрибутив  - его тут вообще нет сейчас в пр

2022-12-21 09:10 UTC, dimakarp1996 commented on annotators/combined_classification/Dockerfile
> +RUN pip install -r requirements.txt
А, просто зависимости ставились 2жды. Второй раз все равно ничегто не ставилось, потому что есть кэш, но убрал 2 строку

2023-01-17 04:44 UTC, dilyararimovna submitted a review, later dismissed

2023-01-24 08:10 UTC, dilyararimovna approved these changes

2023-01-24 08:10 UTC, merged