Fix/facts in travel skill
deeppavlov/dream pull request #239
Opened 2022-11-28 10:47 UTC by Kpetyxova

2022-11-29 04:59 UTC, dilyararimovna requested changes

2022-11-29 04:59 UTC, dilyararimovna commented on skills/dff_travel_skill/dialogflows/flows/travel.py
> +            # LOCATION_FACTS_BUFFER[location] = facts_about_location
а в чем смысл этого фикса? ты просто перестала сохранять в буффер факты о локациях. 
Если это фиксы для того, чтобы факты не повторялись, то надо не тут проверять, а там, где ты конкретный факт вытаскиваешь из буффера

2022-11-29 13:07 UTC, Kpetyxova commented on skills/dff_travel_skill/dialogflows/flows/travel.py
> +            # LOCATION_FACTS_BUFFER[location] = facts_about_location
Сейчас эта функция делает следующее: 
1) пытается достать факт о локации с помощью get_fact_for_particular_entity_from_human_utterance;
2) если НЕ достает (для России вот не достает), то:
* если буфер не пустой, она берет факты из него
* если пустой, то вызывается функция get_fact, которая возвращает ОДИН факт из джейсона с фактами. И ЭТОТ факт кладется в буфер. То есть в следующий раз, когда система захочет рассказать факт о той же локации, сработает ПЕРВОЕ условие (что буфер не пустой), и она тупо достанет из него тот же факт...

Поэтому и фикс такой -- я просто не кладу факт в буфер, чтобы первое условие не отрабатывало. Могу переписать ее целиком, чтобы там вообще не было этого буфера.

А так я думала, что это бага факт ретривера/рандома, но они вообще не причем. Это ошибка именно скилла

2022-11-30 10:25 UTC, dilyararimovna submitted a review, later dismissed

2022-11-30 13:21 UTC, dilyararimovna commented on skills/dff_travel_skill/dialogflows/flows/travel.py
> +            # LOCATION_FACTS_BUFFER[location] = facts_about_location
нееет. Ты все не так поняла(

2022-12-01 02:15 UTC, dilyararimovna commented on skills/dff_travel_skill/dialogflows/flows/travel.py
> +            # LOCATION_FACTS_BUFFER[location] = facts_about_location
короче, тут была неверно использована функция Дениса. Она брала элемент из листа. А по факту надо было просто брать неисопльзованный факт. поправила

2022-12-01 02:15 UTC, merged