changed spelling_preprocessing_ru in order to work with english too (using brill&moore)
deeppavlov/dream pull request #246
Opened 2022-12-02 10:02 UTC by Kpetyxova

2022-12-02 14:44 UTC, dilyararimovna requested changes

2022-12-02 14:44 UTC, dilyararimovna commented on annotators/spelling_preprocessing_ru/requirements.txt
> +lxml
зафиксировать версию

2022-12-02 14:44 UTC, dilyararimovna commented on assistant_dists/dream/docker-compose.override.yml
> +      dockerfile: annotators/spelling_preprocessing_ru/Dockerfile
а давай папку переназовем `_dp` вместое `_ru`

2022-12-05 01:42 UTC, dilyararimovna requested changes
- некоторые файлы остались в spelling_preprocessing_ru папке
- версия не зафиксирована
- поищи по всему дриму, где используется spelling_preprocessing_ru - наверняка в dream_russian/dev.yml тоже вроде есть
- давай в dream_mini тоже заиспользуем эту версию спеллчекера. Спасибо!

2022-12-05 01:42 UTC, dilyararimovna commented on annotators/spelling_preprocessing_ru/requirements.txt
> +lxml
не зафиксировано же, поправить

2022-12-05 01:42 UTC, dilyararimovna commented on assistant_dists/dream/proxy.yml
> +  #     - PORT=8074
отменить. Это же для отладки было у тебя

2022-12-05 08:05 UTC, Kpetyxova commented on annotators/spelling_preprocessing_ru/requirements.txt
> +lxml
точно, я только в dp поправила

2022-12-06 02:51 UTC, dilyararimovna requested changes

2022-12-06 08:55 UTC, Kpetyxova commented on assistant_dists/deepy_gobot_base/docker-compose.override.yml
> +      context: annotators/spelling_preprocessing_dp
потому что я гений. поправлю конечно

2022-12-19 03:11 UTC, dilyararimovna submitted a review, later dismissed

2022-12-20 02:56 UTC, merged