fix: dockerfiles and requirements for nemo and asr_tts
deeppavlov/dream pull request #266
Opened 2022-12-16 08:13 UTC by Kpetyxova

2022-12-16 10:04 UTC, IgnatovFedor requested changes

2022-12-16 10:04 UTC, IgnatovFedor commented on services/speech/thirdparty/clone_tts/Dockerfile
> +    apt-get install unzip \
why?

2022-12-16 10:04 UTC, IgnatovFedor commented on services/speech/thirdparty/clone_tts/requirements.txt
> +resampy==0.3.1.
```suggestion
resampy==0.3.1
```

2022-12-16 10:04 UTC, IgnatovFedor commented on services/speech/thirdparty/nemo/requirements.txt
> +resampy==0.3.1.
```suggestion
resampy==0.3.1
```

2022-12-20 03:15 UTC, dilyararimovna approved these changes

2022-12-20 04:55 UTC, merged