Upd/dff/template skill
deeppavlov/dream pull request #303
Opened 2023-01-26 17:06 UTC by ruthenian8

Update dff_template_skill

2023-01-26 17:40 UTC, kudep requested changes

2023-01-26 17:40 UTC, kudep commented on skills/dff_template_skill/Dockerfile
> +COPY common/dff_release/requirements.txt .
```suggestion
COPY common/dff_api_v1/requirements.txt .
```

2023-01-26 17:40 UTC, kudep commented on skills/dff_template_skill/server.py
> +            responses.append(get_response(ctx, pipeline.actor))
```suggestion
            response = run_dff(ctx, pipeline) # prepare db, run pipeline, get response
            responses.append(response)
```

2023-01-26 17:40 UTC, kudep commented on skills/dff_template_skill/server.py
> +from common.dff_release.integration.serializer import load_ctxs, get_response
```suggestion
from common.dff_release.integration.serializer import load_ctxs, run_dff

```

2023-01-26 17:40 UTC, kudep commented on skills/dff_template_skill/tests/lets_talk_out.json
> +                                "misc": null,
как говолрили можно избавиться от   `null` - полей

2023-01-27 10:16 UTC, ruthenian8 commented on skills/dff_template_skill/Dockerfile
> +COPY common/dff_release/requirements.txt .
Done

2023-01-27 10:16 UTC, ruthenian8 commented on skills/dff_template_skill/server.py
> +            responses.append(get_response(ctx, pipeline.actor))
Done

2023-01-27 10:17 UTC, ruthenian8 commented on skills/dff_template_skill/tests/lets_talk_out.json
> +                                "misc": null,
Done

2023-01-27 10:48 UTC, ruthenian8 commented on common/dff_api_v1/integration/serializer.py
> +    return response
зачем?

2023-01-27 10:49 UTC, ruthenian8 commented on skills/dff_template_skill/scenario/main.py
>                  # "fill_responses_by_slots": int_prs.fill_responses_by_slots(),
почему?

2023-01-27 10:59 UTC, ruthenian8 commented on skills/dff_template_skill/scenario/main.py
> +            PRE_TRANSITIONS_PROCESSING: {"set_confidence": int_prs.set_confidence(0.0)},
В дриме зачем-то сделали 2 способа передавать конфиденс - может быть, один из них надо упразднить, но это надо обсуждать, наверное

2023-01-27 11:16 UTC, kudep commented on skills/dff_template_skill/scenario/main.py
> +            PRE_TRANSITIONS_PROCESSING: {"set_confidence": int_prs.set_confidence(0.0)},
Пусть конфиденс всегда будет явно передаваться с msg

2023-01-27 11:19 UTC, ruthenian8 commented on skills/dff_template_skill/tests/lets_talk_out.json
> +                                        "misc": {
это не отдаваемые сообщения, это сериализованный контекст в состоянии сервиса. Сообщения отдаются в прежнем формате в начале json-а (см. первый список)
![image](https://user-images.githubusercontent.com/45140209/215073952-1d556359-bd0d-492c-9388-7d6941d80095.png)

2023-01-27 11:21 UTC, ruthenian8 commented on skills/dff_template_skill/scenario/main.py
> +            PRE_TRANSITIONS_PROCESSING: {"set_confidence": int_prs.set_confidence(0.0)},
тогда эту функцию можно удалить

2023-01-27 11:24 UTC, kudep commented on skills/dff_template_skill/scenario/main.py
> +            PRE_TRANSITIONS_PROCESSING: {"set_confidence": int_prs.set_confidence(0.0)},
Если у нас два способа - один для всего скоупа (flow или node) назначается, "set_confidence": int_prs.set_confidence(1.0), а второй явный способо, которые имеет больший приоритет - передается непосредственно в msg (особенно актуален когда передается несколько кандидатов с разными conf)

2023-01-27 11:25 UTC, kudep commented on skills/dff_template_skill/scenario/main.py
>                  # "fill_responses_by_slots": int_prs.fill_responses_by_slots(),
Ладно, давай не будем убарать, напишем просто коммент, что можно использовать в local, чтобы слоты всегда экстрактились

2023-01-27 11:25 UTC, ruthenian8 commented on skills/dff_template_skill/scenario/main.py
> +            PRE_TRANSITIONS_PROCESSING: {"set_confidence": int_prs.set_confidence(0.0)},
Тогда есть смысл оставить вызов этой функции в примере, чтобы продемонстрировать ее действие

2023-01-27 11:29 UTC, kudep commented on skills/dff_template_skill/tests/lets_talk_out.json
> +                                        "misc": {
а, хорошо, тогда все ок

2023-01-27 11:30 UTC, kudep commented on skills/dff_template_skill/scenario/main.py
> +            PRE_TRANSITIONS_PROCESSING: {"set_confidence": int_prs.set_confidence(0.0)},
Можно, но надо где-нибудь явно конфиденсы передать, можно в Multimsg

2023-01-27 14:04 UTC, ruthenian8 commented on skills/dff_template_skill/scenario/main.py
> +            PRE_RESPONSE_PROCESSING: {
С претранзишеном работает не так, как надо, почему-то: слоты не сохраняются в сериализованном контексте, как сохранялись раньше

2023-02-02 15:19 UTC, kudep commented on skills/dff_template_skill/scenario/main.py
> +            PRE_RESPONSE_PROCESSING: {
Это почему, должен сохраняться, либо в dff баг, либо что-то еще, можешь разобраться

2023-02-02 21:25 UTC, kudep commented on skills/dff_template_skill/scenario/main.py
>                  # "fill_responses_by_slots": int_prs.fill_responses_by_slots(),
Про то, что можно использовать здесь вместо текущих нод

2023-02-03 09:44 UTC, ruthenian8 commented on skills/dff_template_skill/scenario/main.py
>                  # "fill_responses_by_slots": int_prs.fill_responses_by_slots(),
Написал

2023-02-03 09:45 UTC, ruthenian8 commented on skills/dff_template_skill/scenario/main.py
> +            PRE_RESPONSE_PROCESSING: {
Переместил на ноду раньше

2023-02-06 09:30 UTC, kudep requested changes

2023-02-06 09:30 UTC, kudep commented on skills/dff_template_skill/scenario/main.py
> +)
Не недо использовать актора, можно просто использовать https://github.com/deeppavlov/dialog_flow_framework/blob/efce3311c692b2ed70b13c8f4ab574d6b25216f8/examples/pipeline/2_pre_and_post_processors.py#L59

2023-02-06 09:30 UTC, kudep commented on skills/dff_template_skill/scenario/main.py
> +                ]
Думаю стоит добавить комментарии, что аттрибуты для каждого мессаджа переписываю те аттрибуты, которые установлены с помощью прероцессора

2023-02-06 09:30 UTC, kudep commented on skills/dff_template_skill/scenario/main.py
> +                "save_slots_to_ctx": int_prs.save_slots_to_ctx({"topic": "science", "user_name": "Gordon Freeman"})
Стоит допистаь коммент, что здесь мы сохраняем 2 слота и их значения в контекст, далее они нам пригодятся

2023-02-06 09:30 UTC, kudep commented on common/dff_api_v1/integration/serializer.py
> +        return (response.text, confidence, human_attr, {}, hype_attr)
Что если разраб для одиночного сообщения в message укажет can_continue отличный от того, который в hype_attr?

2023-02-06 09:56 UTC, ruthenian8 commented on common/dff_api_v1/integration/serializer.py
> +        return (response.text, confidence, human_attr, {}, hype_attr)
Я старался во всем следовать прежней логике, но тк структура респонса поменялась, внесу исправления

2023-02-06 09:59 UTC, ruthenian8 commented on skills/dff_template_skill/scenario/main.py
> +                "save_slots_to_ctx": int_prs.save_slots_to_ctx({"topic": "science", "user_name": "Gordon Freeman"})
Добавил

2023-02-06 10:00 UTC, ruthenian8 commented on skills/dff_template_skill/scenario/main.py
> +)
Это было нужно для дебага, забыл убрать

2023-02-06 10:08 UTC, ruthenian8 commented on skills/dff_template_skill/scenario/main.py
> +                ]
Добавил

2023-02-06 11:00 UTC, kudep submitted a review, later dismissed

2023-02-21 08:51 UTC, dilyararimovna requested changes

2023-02-21 08:51 UTC, dilyararimovna commented on common/dff_api_v1/requirements.txt
> +git+https://github.com/deeppavlov/dialog_flow_framework@dev
а почему мы ставим вашу dev ветку? надо зафиксировать версию, потому что, если потом будут breaking changes, мы сломаемся

2023-02-21 08:51 UTC, dilyararimovna commented on common/dff_api_v1/requirements.txt
> +six
зафиксировать версию

2023-02-21 08:51 UTC, dilyararimovna commented on skills/dff_template_skill/tests/lets_talk_out.json
> +                                        "text": "Hi, what's up?"
типа аргументы мы выпилили из истории? а где-то есть к ним доступ в другом месте?

2023-02-21 08:51 UTC, dilyararimovna commented on skills/dff_template_skill/scenario/main.py
> +from dff.script import (
этот импорт надо в 14 строку и совместить с импортом там

2023-02-21 08:51 UTC, dilyararimovna commented on common/dff_api_v1/integration/message.py
> +    hype_attr: Optional[dict] = None
а сам текст реплики?

2023-02-21 08:51 UTC, dilyararimovna commented on common/dff_api_v1/integration/message.py
> +    hype_attr: Optional[dict] = None
конфиденс не optional

2023-02-22 08:55 UTC, ruthenian8 commented on common/dff_api_v1/integration/message.py
> +    hype_attr: Optional[dict] = None
> 

Текст есть в классе, от которого наследуется DreamMessage

2023-03-22 18:59 UTC, Kpetyxova approved these changes

2023-03-23 11:01 UTC, NikaSmilga commented on skills/dff_template_skill/scenario/main.py
> +            RESPONSE: MultiMessage(
Прогнала 10 раз, получаю всегда второй вариант, первый -- ни разу

2023-05-22 14:11 UTC, dilyararimovna approved these changes

2023-06-13 07:11 UTC, dilyararimovna commented
@ruthenian8 не билдится контейнер, посмотри, пожалуйста
```
Building dff-template-skill

Step 1/15 : FROM python:3.9.16-slim

 ---> babdc67dc69c

Step 2/15 : WORKDIR /src

 ---> Using cache

 ---> 3443d7040b25

Step 3/15 : COPY common/dff_api_v1/requirements.txt .

 ---> 8fde444f502d

Step 4/15 : RUN pip install -r requirements.txt

 ---> Running in 6228efc7672d

Collecting git+https://github.com/deeppavlov/dialog_flow_framework@13921ae (from -r requirements.txt (line 9))

  Cloning https://github.com/deeppavlov/dialog_flow_framework (to revision 13921ae) to /tmp/pip-req-build-cl79m2fx

  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version

ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.

You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

Service 'dff-template-skill' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

script returned exit code 1
```

2023-06-13 08:19 UTC, ruthenian8 commented
@dilyararimovna Спасибо, поправил.

> @ruthenian8 не билдится контейнер, посмотри, пожалуйста
>

2023-06-15 14:12 UTC, smilni approved these changes
все хорошо, все поднимается и работает, по моим замечаниям все поправлено, по остальным вроде тоже)

2023-06-19 06:34 UTC, merged