WIP: Lightweight DREAM
deeppavlov/dream pull request #368
Opened 2023-03-28 13:50 UTC by dimakarp1996

Lightweight DREAM classifier. Decreased CPU test passing time from 0.53 sec to 0.32 sec. Waiting for the model weights to be moved to share

2023-03-28 14:19 UTC, dimakarp1996 commented
тесты скилла проходят

2023-04-04 11:44 UTC, dilyararimovna requested changes

2023-04-04 11:44 UTC, dilyararimovna commented on annotators/combined_classification_lightweight/Dockerfile
> +RUN pip install git+https://github.com/deeppavlov/DeepPavlov.git@1f0bda76c7c3fd6ccd4a1c0c880c0fffb73522d1
может на новую версию переходить 1.1.1?

2023-04-04 11:44 UTC, dilyararimovna commented on annotators/combined_classification_lightweight/server.py
> +        sentences = [" "]
а зачем тогда что-то делать вообще?надо скипать просто, возвращать дефолтный ответ

2023-04-04 11:44 UTC, dilyararimovna commented on annotators/combined_classification_lightweight/server.py
> +    logger.info(f"combined_classification exec time: {time.time() - t}")
лайтвейт

2023-04-04 11:44 UTC, dilyararimovna commented on annotators/combined_classification_lightweight/server.py
> +    logger.info(f"combined_classification exec time: {time.time() - t}")
лайтвейт

2023-04-04 11:44 UTC, dilyararimovna commented on assistant_dists/dream_mini_lightweight/dev.yml
> +      - 8011:8011
а тебе нужно делать на предложения? если нет, удали

2023-04-04 11:44 UTC, dilyararimovna commented on assistant_dists/dream_mini_lightweight/docker-compose.override.yml
> +    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.pipeline_config=assistant_dists/dream_mini/pipeline_conf.json'
название дистрибутива

2023-04-04 11:44 UTC, dilyararimovna commented on assistant_dists/dream_mini_lightweight/docker-compose.override.yml
> +  combined-classification:
Дима, у нас нынче из-за дрим билдера политика такая, что если у одной и той же компоненты (через подчеркивание которая) есть разные варианты докер контейнеров, то все контейнеры должнгы называться уникально. Поэтому конетйнер назови `combined-classification-tiny`, а компонента остается `combined_classification` в пайплайне

2023-04-04 11:44 UTC, dilyararimovna commented on assistant_dists/dream_mini_lightweight/docker-compose.override.yml
> +        PORT: 8150
у всех тепреь не порт, а SERVICE_PORT - сделай у себя также, пожаоуйста.

2023-04-04 11:44 UTC, dilyararimovna commented on assistant_dists/dream_mini_lightweight/pipeline_conf.json
> +        "description": "Mini version of DeepPavlov Dream Socialbot. This is a generative-based socialbot that uses English DialoGPT model to generate most of the responses. It also contains intent ca
название, описание и размеры надо заменитб

2023-04-04 11:44 UTC, dilyararimovna commented on assistant_dists/dream_mini_lightweight/telegram.yml
> +    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.channel=telegram agent.telegram_token=$TG_TOKEN agent.pipeline_config=assistant_dists/dream_mini/pipeline_conf.json agent.db_confi
название дистрибутива

2023-04-04 11:44 UTC, dilyararimovna commented on assistant_dists/dream_mini_lightweight/docker-compose.override.yml
> +    deploy:
- еще надо в readme внести этот вариант компонента в табличку
- component.yml, pipeline.yml надо создать в папке с компонентой (по аналогии с другими)

2023-04-04 12:42 UTC, dimakarp1996 commented on annotators/combined_classification_lightweight/Dockerfile
> +RUN pip install git+https://github.com/deeppavlov/DeepPavlov.git@1f0bda76c7c3fd6ccd4a1c0c880c0fffb73522d1
Есть

2023-04-04 12:42 UTC, dimakarp1996 commented on annotators/combined_classification_lightweight/server.py
> +        sentences = [" "]
Есть

2023-04-04 12:42 UTC, dimakarp1996 commented on annotators/combined_classification_lightweight/server.py
> +    logger.info(f"combined_classification exec time: {time.time() - t}")
Есть

2023-04-04 12:43 UTC, dimakarp1996 commented on annotators/combined_classification_lightweight/server.py
> +    logger.info(f"combined_classification exec time: {time.time() - t}")
Есть

2023-04-04 21:36 UTC, dimakarp1996 commented on assistant_dists/dream_mini_lightweight/telegram.yml
> +    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.channel=telegram agent.telegram_token=$TG_TOKEN agent.pipeline_config=assistant_dists/dream_mini/pipeline_conf.json agent.db_confi
Есть

2023-04-04 21:40 UTC, dimakarp1996 commented on assistant_dists/dream_mini_lightweight/dev.yml
> +      - "./annotators/combined_classification:/src"
да

2023-04-04 21:43 UTC, dimakarp1996 commented on assistant_dists/dream_mini_lightweight/docker-compose.override.yml
> +        PORT: 8150
ok

2023-04-04 21:44 UTC, dimakarp1996 commented on assistant_dists/dream_mini_lightweight/docker-compose.override.yml
> +    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.pipeline_config=assistant_dists/dream_mini/pipeline_conf.json'
ok

2023-04-04 21:54 UTC, dimakarp1996 commented on assistant_dists/dream_mini_lightweight/docker-compose.override.yml
> +  combined-classification:
ок

2023-04-04 21:54 UTC, dimakarp1996 commented on assistant_dists/dream_mini_lightweight/pipeline_conf.json
> +                "state_manager_method": "add_annotation"
ок

2023-04-04 21:56 UTC, dimakarp1996 commented on assistant_dists/dream_mini_lightweight/pipeline_conf.json
> +        "description": "Mini version of DeepPavlov Dream Socialbot. This is a generative-based socialbot that uses English DialoGPT model to generate most of the responses. It also contains intent ca
Название и описание заменил. Про размеры задал один вопрос Феде

2023-04-05 09:11 UTC, dimakarp1996 commented
test_dialog fail is irrelevant as there only existing combined_classification version performs, and this PR does not change it in any way

2023-04-05 11:33 UTC, dilyararimovna requested changes

2023-04-05 11:33 UTC, dilyararimovna commented on README.md
> +| Combined Classification lightweight    | 1.6 Gb RAM, 0.9 Gb GPU | The same model as Combined Classification, but takes 42% less time thanks to the lighter backbone              |
сделать красиво. пайчарм, например, автоматипчески выравнивает строчки, можно с помощью него

2023-04-05 11:33 UTC, dilyararimovna commented on README.md
> +| Combined Classification lightweight    | 1.6 Gb RAM, 0.9 Gb GPU | The same model as Combined Classification, but takes 42% less time thanks to the lighter backbone              |
GB пожалуйста, нам это потом парсить может понадобиться (а может и нет, но адвай везде одинаково)

2023-04-05 11:33 UTC, dilyararimovna commented on annotators/combined_classification_lightweight/Dockerfile
> +ENV PORT=$PORT
SERVICE_PORT

2023-04-05 11:33 UTC, dilyararimovna commented on annotators/combined_classification_lightweight/Dockerfile
> +WORKDIR /base/DeepPavlov
а зачем? не вижу использование вообще

2023-04-05 11:33 UTC, dilyararimovna commented on annotators/combined_classification_lightweight/component.yml
> +combined-classification:
это контейнер нейм дублируется, так что combined-classification-lightweight

2023-04-05 11:33 UTC, dilyararimovna commented on annotators/combined_classification_lightweight/component.yml
> +    sentiment, toxicity, emotion, factoid classification
инфо про лайтвейт

2023-04-05 11:33 UTC, dilyararimovna commented on annotators/combined_classification_lightweight/pipeline.yml
> +combined-classification:
combined-classification-lightweight

2023-04-05 11:33 UTC, dilyararimovna commented on annotators/combined_classification_lightweight/pipeline.yml
> +    url: http://combined-classification:8150/model
combined-classification-lightweight

2023-04-06 08:57 UTC, dimakarp1996 commented on annotators/combined_classification_lightweight/Dockerfile
> +ENV PORT=$PORT
OK

2023-04-06 08:58 UTC, dimakarp1996 commented on annotators/combined_classification_lightweight/Dockerfile
> +WORKDIR /base/DeepPavlov
OK

2023-04-06 09:00 UTC, dimakarp1996 commented on annotators/combined_classification_lightweight/pipeline.yml
> +    url: http://combined-classification:8150/model
ok

2023-04-06 09:00 UTC, dimakarp1996 commented on annotators/combined_classification_lightweight/pipeline.yml
> +combined-classification:
ok

2023-04-06 09:05 UTC, dimakarp1996 commented on annotators/combined_classification_lightweight/component.yml
> +    sentiment, toxicity, emotion, factoid classification
ок

2023-04-07 07:10 UTC, dilyararimovna approved these changes

2023-04-07 08:49 UTC, dilyararimovna requested changes

2023-04-07 08:49 UTC, dilyararimovna commented on README.md
> +| Combined Classification lightweight | 1.6 GB RAM, 0.9 GB GPU | The same model as Combined Classification, but takes 42% less time thanks to the lighter backbone
так я тут задумалась, а какого лешего занимается память на гпу? мы же договорились, что тут цпу инференс должен быть?

2023-04-08 08:27 UTC, dimakarp1996 commented on README.md
> +| Combined Classification lightweight | 1.6 GB RAM, 0.9 GB GPU | The same model as Combined Classification, but takes 42% less time thanks to the lighter backbone
Если подымать без cpu.yml, то занимается

2023-04-17 12:11 UTC, dilyararimovna commented on README.md
> +| Combined Classification lightweight | 1.6 GB RAM, 0.9 GB GPU | The same model as Combined Classification, but takes 42% less time thanks to the lighter backbone
так надо чтобы по дефолту поднималось без гпу.

2023-06-05 16:47 UTC, closed without merging