WIP: Dockerfiles refactoring
deeppavlov/dream pull request #375
Opened 2023-04-04 12:39 UTC by NeoIsALie

Initial optimization changes in Dream's Dockerfiles. Those changes include merge of multiple `RUN` commands, reducing number of `pip install` 's by extending `requirements.txt` files.

2023-04-12 06:40 UTC, dilyararimovna requested changes

2023-05-29 15:44 UTC, dilyararimovna requested changes

2023-05-29 15:44 UTC, dilyararimovna commented on annotators/IntentCatcherTransformers/requirements.txt
> +git+https://github.com/deeppavlov/DeepPavlov.git@1.1.1
а вроде есть базовый имадж контейнера под 1.1.1 диппавлова

2023-05-31 07:06 UTC, NeoIsALie commented on annotators/IntentCatcherTransformers/requirements.txt
> +git+https://github.com/deeppavlov/DeepPavlov.git@1.1.1
вроде

2023-05-31 15:21 UTC, dilyararimovna approved these changes

2023-05-31 15:21 UTC, merged