Summarization models
deeppavlov/dream pull request #393
Opened 2023-04-16 18:21 UTC by Kolpnick

2023-06-30 16:24 UTC, smilni requested changes

2023-06-30 16:24 UTC, smilni commented on annotators/summarization_annotator/test.py
> +
хоть убей не могу понять почему, но у меня SUMMARIZATION_SERVICE_URL вылезает как None, из-за чего ломается тест, пытаясь пересказать русский текст. проверь плиз работает ли все у тебя, если работает, давай спишемся попытаемся понять в чем у меня дело.

2023-06-30 16:24 UTC, smilni commented on annotators/summarization_annotator/server.py
> +        return summary
почему именно на 11? то есть пересказываем всего один раз за диалог, когда получаем 11 реплик?

2023-06-30 16:24 UTC, smilni commented on annotators/summarization_annotator/server.py
> +    dialog = dialog[:6]
почему всегда первые 6 реплик? а куда деваются последние 6?

2023-06-30 16:24 UTC, smilni commented on annotators/summarization_annotator/pipeline.yml
> +    timeout: 2.0
в других местах у тебя другой таймаут у summarization-annotator

2023-06-30 16:24 UTC, smilni commented on services/brio_summarizer/pipeline.yml
> +    timeout: 2.0
мало

2023-06-30 16:24 UTC, smilni commented on services/ruT5_summarizer/pipeline.yml
> +    timeout: 2.0
тоже мало

2023-06-30 16:27 UTC, smilni commented on annotators/summarization_annotator/server.py
> +        return summary
кажется это связано с тем, что ты подаешь 11 реплик только каждые пять реплик. Но зачем на каждой пятой реплике ты подаешь именно 11 реплик? и почему потом пересказываешь первые шесть?

2023-06-30 16:27 UTC, smilni commented on annotators/summarization_annotator/server.py
> +        return summary
я очень запуталась, можешь плиз объяснить идею и логику?

2023-06-30 16:32 UTC, smilni commented on annotators/summarization_annotator/component.yml
> +  ram_usage: 1G
так много? в докер-компоуз файле 256мб

2023-06-30 16:34 UTC, smilni commented
еще -- подмержь свежий дев, разреши конфликт. посмотри на то, как изменились карточки, сделай по образцу сервисов и аннотаторов в деве. добавь карточки в папку components, порты в файл components.tsv (проверь чтоб твои были незаняты, кстати)

2023-07-04 09:31 UTC, Kolpnick commented on annotators/summarization_annotator/component.yml
> +  ram_usage: 1G
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/8c54ef865a93c3478ac29f2e1e1e442e67e4960a)

2023-07-04 09:32 UTC, Kolpnick commented on services/ruT5_summarizer/pipeline.yml
> +    timeout: 2.0
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/8c54ef865a93c3478ac29f2e1e1e442e67e4960a)

2023-07-04 09:32 UTC, Kolpnick commented on services/brio_summarizer/pipeline.yml
> +    timeout: 2.0
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/8c54ef865a93c3478ac29f2e1e1e442e67e4960a)

2023-07-04 09:32 UTC, Kolpnick commented on annotators/summarization_annotator/pipeline.yml
> +    timeout: 2.0
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/8c54ef865a93c3478ac29f2e1e1e442e67e4960a)

2023-07-04 09:32 UTC, Kolpnick commented on annotators/summarization_annotator/server.py
> +        summary = requests.post(SUMMARIZATION_SERVICE_URL, json={"sentences": dialog}, timeout=3).json()[0]['batch']
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/8c54ef865a93c3478ac29f2e1e1e442e67e4960a)

2023-07-12 12:11 UTC, smilni commented on annotators/summarization_annotator/component.yml
> +  ram_usage: 1G
256мб, не гб 😦

2023-07-12 12:12 UTC, smilni commented on annotators/summarization_annotator/server.py
прости, что не сказала сразу, но все таймауты лучше параметрами задавать, чтоб они менялись из докер-компоуз файла. сделай плиз что-то типа timeout=REQUEST_TIMEOUT

2023-07-12 17:32 UTC, smilni commented on assistant_dists/dream/pipeline_conf.json
> +                    "endpoint": "respond"
посмотри как это сделано в других сервисах, сделай по аналогии. карточки сейчас обязательны для всего

2023-07-13 12:18 UTC, smilni commented
пожалуйста, подмержь свежий дев! и в целом каждый раз когда вносишь изменения, 1) подмерживай дев, 2) разрешай конфликты, если они есть (щас их много)

2023-07-13 12:50 UTC, smilni commented on assistant_dists/dream/pipeline_conf.json
> +                    "endpoint": "respond"
то же самое про русский дрим

2023-07-13 12:53 UTC, smilni commented on annotators/summarization_annotator/server.py
> +    return jsonify(summarization_attribute)
ты проверил что в результате выходит? смотри, щас проблема в том, что ты каждый раз перезаписываешь пересказ. надо не перезаписывать, надо аппендить. то есть чтоб у тебя было
реплика 11: bot_attr: {"summary": "1-6"} 
реплика 13: bot_attr: {"summary": "1-6"}
реплика 15: bot_attr: {"summary": "1-6"}
реплика 17: bot_attr: {"summary": "1-6 + 7-12"}

а сейчас у тебя
реплика 11: bot_attr: {"summary": "1-6"} 
реплика 13: bot_attr: {"summary": ""}
реплика 15: bot_attr: {"summary": ""}
реплика 17: bot_attr: {"summary": "7-12"}

2023-07-13 12:54 UTC, smilni commented on annotators/summarization_annotator/server.py
> +    return jsonify(summarization_attribute)
могу предложить переделать форматтер для этого аннотатора, чтоб в нем всегда подавался пересказ. и тогда делать final_result = previous_summary_from_formatter + result_this_summary

2023-07-13 12:56 UTC, smilni commented on annotators/summarization_annotator/server.py
> +    return jsonify(summarization_attribute)
если есть вопросы с тем как проверять результат: берешь любой форматтер, идущий после твоего аннотатора, и добавляешь туда строки     
```
with open('test_dialog.json', 'w') as f:
        json.dump(dialog, f, ensure_ascii=False, indent=4)
```
     
я например брала full_history_formatter

2023-07-13 14:44 UTC, smilni commented
Общий комментарий по архитектуре -- ты не совсем правильно работаешь с батчами.
Во-первых, в форматтерах по аналогии с другими (utt_sentseg_punct_dialog, full_dialog, etc.) возвращай [{"dialogs": [dialog]}]
И тогда в аннотаторе соответственно доставай и обрабатывай батч (request.json.get('dialogs', [])), а не один диалог

2023-07-20 06:59 UTC, Kolpnick commented on annotators/summarization_annotator/component.yml
> +  ram_usage: 1G
Не заметил)) Но данный файл всё равно был удалён при изменении карточек в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/9ba8452202d71ae9042c4aa4372dd5564b6a5636)

2023-07-20 10:04 UTC, Kolpnick commented on annotators/summarization_annotator/server.py
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/9ca6ad8edb47d99a43243d308a5f102714d7c1af)

2023-07-20 10:05 UTC, Kolpnick commented on assistant_dists/dream/pipeline_conf.json
> +                    "endpoint": "respond"
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/c60225ceb64783e01100fe895bc56bf032940372)

2023-07-20 10:05 UTC, Kolpnick commented on annotators/summarization_annotator/server.py
> +    return jsonify(summarization_attribute)
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/e7446577b48ab15bf7fd63681fa6f1f25f1cfa16)

2023-07-24 12:27 UTC, smilni commented on annotators/summarization_annotator/server.py
> +        result += prev_summary
может просто result = prev_summary вместо двух строк?

2023-07-24 12:27 UTC, smilni commented on annotators/summarization_annotator/server.py
> +        result = result.strip()
я бы заменила на 
```
if new_summary:
  result = f"{result} {new_summary}".strip()
```

2023-07-24 12:27 UTC, smilni commented on services/dialog_summarizer/server.py
> +    tokenized_text = tokenizer(sentences, max_length=512, return_tensors="pt", truncation=True,
а почему больше 512 не может быть?

2023-07-24 14:31 UTC, Kolpnick commented on assistant_dists/dream/docker-compose.override.yml
> +  summarization-annotator:
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/8d1f4842952ba4826491e8fde2eb616580f75e8c)

2023-07-24 14:31 UTC, Kolpnick commented on annotators/summarization_annotator/server.py
> +        result += prev_summary
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/8d1f4842952ba4826491e8fde2eb616580f75e8c)

2023-07-24 14:32 UTC, Kolpnick commented on services/dialog_summarizer/server.py
> +    tokenized_text = tokenizer(sentences, max_length=512, return_tensors="pt", truncation=True,
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/8d1f4842952ba4826491e8fde2eb616580f75e8c)

2023-08-04 13:11 UTC, dilyararimovna requested changes
почти все, пару вопросов и все

2023-08-04 13:11 UTC, dilyararimovna commented on annotators/summarization_annotator/server.py
> +        logger.info(f"summarization-annotator received previous summary: {[prev_summary]}")
мб перевести в режим debug эти два лога, а то логи будут быстро разрастаться

2023-08-04 13:11 UTC, dilyararimovna commented on annotators/summarization_annotator/server.py
> +        logger.info(f"summarization-annotator output: {summarization_attribute}")
ну или оставить только этот принт что ли

2023-08-04 13:11 UTC, dilyararimovna commented on annotators/summarization_annotator/server.py
> +    summary = []
почему дефолтное значение лист, если обычно там строка лежит? надо пустую строку сделать дефолтным значением тогда

2023-08-04 13:34 UTC, Kolpnick commented on annotators/summarization_annotator/server.py
> +        logger.info(f"summarization-annotator received previous summary: {[prev_summary]}")
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/03b675f795076789a3b69478a56b6f5eeca1c8d0)

2023-08-04 13:34 UTC, Kolpnick commented on annotators/summarization_annotator/server.py
> +    summary = []
Исправил в [коммите](https://github.com/deeppavlov/dream/pull/393/commits/03b675f795076789a3b69478a56b6f5eeca1c8d0)

2023-08-04 13:38 UTC, dilyararimovna approved these changes

2023-08-04 13:38 UTC, merged