Odqa with llm
deeppavlov/dream pull request #412
Opened 2023-04-25 15:43 UTC by smilni

rn sentence ranker and combined classification are down, so when checking build locally

2023-04-26 08:23 UTC, NeoIsALie requested changes

2023-04-26 08:23 UTC, NeoIsALie commented on services/doc_ranker/Dockerfile
> +RUN spacy download en_core_web_sm
Можно собрать в один RUN, скачивание en_core_web_sm можно вынести в requirements.txt

2023-04-26 08:23 UTC, NeoIsALie commented on skills/dff_qa_llm_skill/Dockerfile
> +RUN python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"
Можно объединить.

2023-05-03 08:08 UTC, dilyararimovna reviewed
- 8150 вроде занят
- название контейнера должно быть уникальным для компоненты с ее уникальными параметрами
- в каждой папке компоненты теперь есть папка service_configs, в ней есть подпапки с названиями контейнеров, в каждой подпапке есть environment.yml, service.yml. 
- тебе нужно для каждой твоей новой компоненты нужно создать эти подпапки и файлики yml.
- есть в корне дрим папка components, в ней есть странные файлы с длинными названиями *.yml. Тебе нужно под каждую новую компоненту создать свой такой файлик. только буквы и цифры в названии файла случайно, без символов.  Обрати внимание на то, как поменялся source в pipeline_conf.json - переделай

2023-05-18 16:02 UTC, Kpetyxova commented on assistant_dists/QA_doc/docker-compose.override.yml
> +    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.pipeline_config=assistant_dists/universal_prompted_assistant/pipeline_conf.json'
QA_doc наверное

2023-05-18 16:03 UTC, Kpetyxova commented on assistant_dists/QA_doc/telegram.yml
> +    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.channel=telegram agent.telegram_token=$TG_TOKEN agent.pipeline_config=assistant_dists/universal_prompted_assistant/pipeline_conf.j
QA_doc

2023-05-18 16:06 UTC, Kpetyxova commented on skills/dff_qa_llm_skill/scenario/response.py
> +DEFAULT_PROMPT = "Answer questions based on parts of a financial report."
а почему такой промпт?

2023-05-18 16:58 UTC, Kpetyxova commented on skills/dff_qa_llm_skill/scenario/response.py
> +        context[
Обязательно нужно смотреть на конфиденс, возвращаемый док ранкером. Если он ниже какого-то порога -- то использовать какой-нибудь промпт заглушку типо "чел задал такой-то вопрос, но в твоей базе данных не на него ответа -- вежливо скажи об этом человеку". потому что сейчас если задать вопрос не по теме, то получится хрень

2023-05-18 16:59 UTC, Kpetyxova commented on skills/dff_qa_llm_skill/server.py
> +
хотя он вроде достаточно быстро билдится, можно и забить наверное

2023-05-18 17:02 UTC, Kpetyxova commented on assistant_dists/QA_doc/proxy.yml
> +
еще кстати когда подмержишь дев, надо будет proxy.deeppavlov.ai использовать везде

2023-06-06 15:01 UTC, Kpetyxova requested changes

2023-06-06 15:01 UTC, Kpetyxova commented on state_formatters/dp_formatters.py
> +        "dff_universal_prompted_skill",
dff_qa_llm_skill

2023-06-06 15:15 UTC, smilni commented on assistant_dists/QA_doc/pipeline_conf.json
> +    "candidate_annotators": {
нет, они ломают все. не дают репликам со словом fat например вылезать, а если это реплики про питание?)) у меня чатгпт как бэкбоун, она и так супер toxic-proof

2023-06-06 15:28 UTC, smilni commented on annotators/entity_detection/server.py
> +            for (entity_substr_list, tags_list, probas_list, entity_offsets_list, uttr, num,) in zip(
блин надо его поправить уже, его постоянно блэк исправляет и каждый блин раз я случайно его пушу

2023-06-06 15:34 UTC, Kpetyxova commented on annotators/doc_retriever/server.py
> +        db_file = requests.get(db_link)
да никак на самом деле, там и так все в try except завернуто, я скорее из интереса спросила. Но смотри, у тебя если упадет try, то у тебя на самом деле упадет вся функция, потому что ты ranker_model задаешь только внутри эксепта, а в строке 72 обращаешься. вот это бы ндо поправить, по-хорошему, чтобы не падало, а results просто были пустые

2023-06-06 15:34 UTC, Kpetyxova commented on skills/dff_qa_llm_skill/scenario/response.py
> +    context = int_ctx.get_utterances(ctx, actor)[-N_UTTERANCES_CONTEXT:]
а, четко

2023-06-06 15:47 UTC, smilni commented on annotators/doc_retriever/server.py
> +        db_file = requests.get(db_link)
посмотри, пжл, так норм?

2023-06-07 08:10 UTC, dilyararimovna requested changes
![image](https://github.com/deeppavlov/dream/assets/14152126/4ee199a8-9b19-43c1-aec9-70aef8bcf8a7)

2023-06-07 12:42 UTC, smilni commented on assistant_dists/QA_doc/docker-compose.override.yml
> +    deploy:
не вижу ничего кроме лимитов... их поправлю

2023-06-07 12:56 UTC, smilni commented on assistant_dists/QA_doc/docker-compose.override.yml
> +        N_UTTERANCES_CONTEXT: 7
упс

2023-06-07 13:38 UTC, Kpetyxova commented on annotators/doc_retriever/server.py
> +        db_file = requests.get(db_link)
да

2023-07-03 10:00 UTC, dilyararimovna commented on components/ogniUFYVoebnIBDUEyV56vefwiu.yml
> +display_name: DFF QA LLM-based Skill
LLM-based Q&A on Documents Skill мб?

2023-07-03 10:00 UTC, dilyararimovna commented on components/ogniUFYVoebnIBDUEyV56vefwiu.yml
> +dialog_formatter: state_formatters.dp_formatters:dff_prompted_skill_formatter
там еще имя скилла надо подавать

2023-07-03 10:03 UTC, dilyararimovna commented on skill_selectors/description_based_skill_selector/connector.py
> +                set(all_skill_names).difference(set(prompted_skills) | set("dff_document_qa_llm_skill"))
слишком усложняет логику для взгляда. 
что ты хочешь тут сделать? добавить dff_document_qa_llm_skill в not_prompted_skills? так он и так там должен быть вроде - разве нет?

2023-07-03 10:16 UTC, dilyararimovna commented on skills/dff_document_qa_llm_skill/scenario/response.py
> +            orig_file = requests.get(filepath, timeout=30)
таймаут в параметры

2023-07-03 10:18 UTC, dilyararimovna commented on skills/dff_document_qa_llm_skill/scenario/response.py
> +        ] = f"""Text: ### {final_candidates} ###
оч не красиво, что промпт тут. надо положить его в файл json и подгружать. а название файла давать как параметр

2023-07-03 10:19 UTC, dilyararimovna commented on skills/dff_document_qa_llm_skill/service_configs/dff-document-qa-llm-skill/service.yml
> +  - PROXY_PASS=dream.deeppavlov.ai:8166
прокси нет с ним и не будет

2023-07-03 15:19 UTC, smilni commented on annotators/doc_retriever/server.py
> +                if dialog.get("human_attributes", [])[-1].get("documents", []) != attributes.get(
а тут сначала проверка же что не пустой список (см строкой выше)
если пустой, мы не попадем в 151. надо наверное вообще дефолтное убрать?..

2023-07-03 15:20 UTC, smilni commented on annotators/doc_retriever/server.py
> +                if dialog.get("human_attributes", [])[-1].get("documents", []) != attributes.get(
в остальных вроде отслеживала это, но еще перепроверю

2023-07-03 15:23 UTC, smilni commented on annotators/doc_retriever/service_configs/doc-retriever/service.yml
> +    - PROXY_PASS=dream.deeppavlov.ai:8165
ой упс

2023-07-03 15:34 UTC, smilni commented on annotators/doc_retriever/service_configs/doc-retriever/environment.yml
> +DOC_PATH_OR_LINK: http://files.deeppavlov.ai/dream_data/documents_for_qa/the_little_prince_book.txt,http://files.deeppavlov.ai/dream_data/documents_for_qa/alphabet_financial_report.txt,http://files.d
добавила, а тут что-то заменить? можно прям лист бахнуть? 
DOC_PATH_OR_LINK: [1.txt, 2.txt, 3.txt]?

2023-07-03 16:07 UTC, smilni commented on annotators/doc_retriever/test.py
> +    url = "http://0.0.0.0:{SERVICE_PORT}/return_candidates"
а как его тестить? там просто идет работа с файлами (тренируется и загружается модель), и тест во-первых будет долгий, во-вторых есть ли файл который гарантированно никуда не денется?

2023-07-03 16:08 UTC, smilni commented on annotators/doc_retriever/test.py
> +    url = "http://0.0.0.0:{SERVICE_PORT}/return_candidates"
могу в теории на файл сервер файл в одну строку закинуть, чтоб тест был быстрый

2023-07-03 16:53 UTC, smilni commented on components/ogniUFYVoebnIBDUEyV56vefwiu.yml
> +dialog_formatter: state_formatters.dp_formatters:dff_prompted_skill_formatter
не могу найти пример, во всех карточках вижу такое же: https://github.com/deeppavlov/dream/blob/1ce25e9de427232e90ab9860d0460397801fe770/components/6lLhP7zuoiI0bxJEDLWUg.yml#L17

2023-07-03 16:53 UTC, smilni commented on skill_selectors/description_based_skill_selector/connector.py
> +                set(all_skill_names).difference(set(prompted_skills) | set("dff_document_qa_llm_skill"))
наоборот, исключить. типа not_prompted_skills это все скиллы кроме (prompted_skills+dff_document_qa_llm_skill). чтоб он не лез когда не надо. но я согласна что выглядит уродски, я сначала сама не поняла, что тут. ща сделаю понятнее

2023-07-03 16:53 UTC, smilni commented on skill_selectors/description_based_skill_selector/connector.py
> +                set(all_skill_names).difference(set(prompted_skills) | set("dff_document_qa_llm_skill"))
сделала через .remove в след строке

2023-07-03 16:53 UTC, smilni commented on annotators/doc_retriever/server.py
> +    return jsonify(attributes_to_add)
нужно обсудить на созвоне

2023-07-06 13:10 UTC, dilyararimovna requested changes

2023-07-06 13:10 UTC, dilyararimovna commented on components/nlknkn768678DUFYbcjk.yml
> +  timeout: 30.0
тут другое время. првоерь все атймауты для скилла и ретривера везде

2023-07-06 13:10 UTC, dilyararimovna commented on skills/dff_document_qa_llm_skill/scenario/response.py
> +    DOCUMENT_PROMPT_TEXT = json.load(f)["prompt"]
у тебя запрос в генеративный сервис шлется с DEFAULT_SYSTEM_PROMPT ниже, а этот промпт добавляется в контекст  DOCUMENT_PROMPT_TEXT

2023-07-06 13:10 UTC, dilyararimovna commented on components/ogniUFYVoebnIBDUEyV56vefwiu.yml
> +  skill_name: dff_dream_persona_prompted_skill
dff_document_qa_llm_skill

2023-07-06 22:10 UTC, smilni commented on annotators/doc_retriever/service_configs/doc-retriever/service.yml
> +        - http://files.deeppavlov.ai/dream_data/documents_for_qa/test_file_jurafsky_chatbots.pdf
блин я вообще забыла эти пути обсудить. завтра на созвоне

2023-07-06 22:11 UTC, smilni commented on skills/dff_document_qa_llm_skill/scenario/response.py
> +    DOCUMENT_PROMPT_TEXT = json.load(f)["prompt"]
так и надо)
у меня большой текст был, ты попросила его убрать, я вынесла в файл

2023-07-06 22:12 UTC, smilni commented on skills/dff_document_qa_llm_skill/scenario/response.py
> +    DOCUMENT_PROMPT_TEXT = json.load(f)["prompt"]
хотя блин уже не уверена что так надо. но так задумано и так работает, поэтому предлагаю пока что оставить атк

2023-07-06 22:31 UTC, smilni commented on components/nlknkn768678DUFYbcjk.yml
> +  timeout: 30.0
<img width="610" alt="Screenshot 2023-07-07 at 01 31 01" src="https://github.com/deeppavlov/dream/assets/42929200/61776fc8-a752-4e6b-a761-8fb8853cd326">
вроде у этого эндпойнта такое и есть

2023-07-07 09:46 UTC, dilyararimovna approved these changes

2023-07-07 09:52 UTC, merged