Add/api skill
deeppavlov/dream pull request #460
Opened 2023-05-18 09:20 UTC by Kpetyxova

distribution with skill that can use several APIs to handle requests

2023-06-06 14:59 UTC, smilni commented on components/jlWY3GplgG.yml
> +    LangChain's GoogleSearchAPIWrapper to use Google search and OpenAI llm
OpenAI LLM - or better to specify which one

2023-06-13 15:19 UTC, smilni requested changes
1. You (pnfvnrfiongibip3ogrn): what is the weather in Moscow?
Bot:  Currently I have problems with getting weather in Is. But I would guess... Skittles chewies falling is possible. . And the temperature may be around 50 degrees Fahrenheit. Would you enjoy it?

Неправильно реагирует на простой запрос (хотя верно выбрал openai-api result: [['weather_api']]). Плюс в заглушке что-то некрасивое с пунктуацией

You (lrgk;nblknrlkbnlkrenlknrlek): will it snow tomorrow in Tbilisi?
Bot:  Hi, this is a Dream Socialbot! It is overcast clouds, temperature is around 61.9 degrees Fahrenheit in Snov. Wind speed is about 1.4 meters per second

я бы сказала, что беда с NER, но не вижу чтоб он использовал NER. короче пока что он мне ни на один полноценный запрос пока не ответил, кроме "weather moscow'

2. OPENWEATHERMAP_API_KEY может в envvars запихнуть в докер-компоузе? а то он мне встретился только в логах ошибки, непонятно было, что он вообще нужен

2023-06-13 15:19 UTC, smilni commented on assistant_dists/dream_apis/dev.yml
> +      - 8018:8018
я бы их выпилила чтоб не банили слова типа fat, часто false positives у него. но это надо у Дили уточнить

2023-06-13 15:19 UTC, smilni commented on skills/dff_api_skill/component.yml
> +    ENVVARS_TO_SEND: OPENAI_API_KEY,GOOGLE_CSE_ID,GOOGLE_API_KEY
в докеркомпоузе у тебя еще OPENAI_ORGANIZATION

2023-06-13 15:19 UTC, smilni commented on skills/dff_api_skill/component.yml
> +    to use Google search and OpenAI llm for question answering.
LLMs

2023-06-13 15:19 UTC, smilni commented on skills/dff_api_skill/component.yml
> +    ENVVARS_TO_SEND: OPENAI_API_KEY,GOOGLE_CSE_ID,GOOGLE_API_KEY
в докеркомпоуз файле у этого скилла гораздо больше аргументов (конфиг и тд)

2023-06-13 15:19 UTC, smilni commented on skills/dff_api_skill/scenario/response.py
> +assert sending_variables["OPENAI_ORGANIZATION"], logger.info("Type in OPENAI ORGANIZATION key to `.env_scret`")
необязательная переменная, другие скиллы без нее работают

2023-06-13 15:23 UTC, smilni commented on skills/dff_api_skill/service_configs/dff-api-skill/environment.yml
> +proxy: null
что-то тут не то, кажется, случайно вышла копия service.yml

2023-06-13 15:25 UTC, smilni commented on skills/dff_api_skill/component.yml
> +  ram_usage: 150M
в других местах по-другому

2023-06-13 15:28 UTC, smilni commented on skills/dff_api_skill/scenario/response.py
> +              DON'T EXPLAIN YOUR DECISION, JUST RETURN THE KEY. E.x. google_api"""
убери отступы, иначе тратим токены
<img width="1045" alt="Screenshot 2023-06-13 at 18 28 08" src="https://github.com/deeppavlov/dream/assets/42929200/a4d100e5-2813-40fe-9e8b-b7ddf9ccb9a8">

2023-06-13 15:29 UTC, smilni commented on skills/dff_api_skill/scenario/response.py
> +              DON'T EXPLAIN YOUR DECISION, JUST RETURN THE KEY. E.x. google_api"""
убери отступы, иначе тратим токены лишние
<img width="1033" alt="Screenshot 2023-06-13 at 18 28 59" src="https://github.com/deeppavlov/dream/assets/42929200/7ac34e77-2203-49ed-aba5-87ed21f97e49">

2023-06-13 15:32 UTC, smilni commented on skills/dff_api_skill/generative_configs/default_generative_config.json
> +}
конфиги теперь из коммона берутся

2023-06-13 15:34 UTC, smilni commented on skills/dff_api_skill/pipeline.yml
> +    timeout: 5.0
точно 5? в пайплайн-конфе 10 для апи-скилла

2023-06-15 12:15 UTC, Kpetyxova commented on assistant_dists/dream_apis/dev.yml
> +      - 8018:8018
да выпилю

2023-06-15 12:29 UTC, smilni commented on assistant_dists/dream_apis/docker-compose.override.yml
> +          memory: 128M
да вот я тоже не въехала. тем не менее без памяти не поднялся ни разу

2023-06-15 12:50 UTC, Kpetyxova commented on skills/dff_api_skill/service_configs/dff-api-skill/environment.yml
> +proxy: null
whoooopsie

2023-06-15 13:34 UTC, Kpetyxova commented on skills/dff_api_skill/scenario/response.py
> +}
не получится, там эти функции еще не определены

2023-06-19 15:07 UTC, smilni requested changes

2023-06-19 15:07 UTC, smilni commented on assistant_dists/dream_apis/pipeline_conf.json
> +                    "timeout": 10.0,
могу ошибаться, но если generative_timeout=15, разве у нас не будет ситуаций, когда скилл упал на 10й секунде (тк тут таймаут 10), а внутри него генеративный сервис ответил скажем на 13й? то есть мой пойнт в том, что не должно ли тут быть больше чем generative_timeout секунды на 3-5? я не уверена, поправь если что

2023-06-19 15:07 UTC, smilni commented on components/jlWY3GplgG.yml
> +  timeout: 15.0
у тебя у самого скилла таймаут 10. а генеративный 15, но это просто аргумент

2023-06-19 15:07 UTC, smilni commented on skills/dff_api_skill/component.yml
> +  ram_usage: 150M
здесь не то же самое должно быть что в лимитах в докерфайле? (256)

2023-06-19 15:07 UTC, smilni commented on skills/dff_api_skill/component.yml
> +    ENVVARS_TO_SEND: OPENAI_API_KEY,GOOGLE_CSE_ID,GOOGLE_API_KEY
добавь его) он не обязателен, но может посылаться. в скиллах-образцах он есть в ENVVARS_TO_SEND

2023-06-19 15:07 UTC, smilni commented on skills/dff_api_skill/service_configs/dff-api-skill/service.yml
> +      ENVVARS_TO_SEND: OPENAI_API_KEY,GOOGLE_CSE_ID,GOOGLE_API_KEY
опять нет организации

2023-06-19 15:07 UTC, smilni commented on skills/dff_api_skill/service_configs/dff-api-skill/service.yml
> +        memory: 128M
у тебя выше 256

2023-06-19 15:21 UTC, Kpetyxova commented on skills/dff_api_skill/service_configs/dff-api-skill/service.yml
> +      ENVVARS_TO_SEND: OPENAI_API_KEY,GOOGLE_CSE_ID,GOOGLE_API_KEY
так я ее убрала везде

2023-06-19 15:29 UTC, smilni commented on skills/dff_api_skill/service_configs/dff-api-skill/service.yml
> +      ENVVARS_TO_SEND: OPENAI_API_KEY,GOOGLE_CSE_ID,GOOGLE_API_KEY
ее не надо убирать, просто ассерты убрать

2023-06-19 15:29 UTC, smilni commented on skills/dff_api_skill/service_configs/dff-api-skill/service.yml
> +      ENVVARS_TO_SEND: OPENAI_API_KEY,GOOGLE_CSE_ID,GOOGLE_API_KEY
я выше писала. ее может не быть и это не мешает, но она может и подаваться. ты спрашивала у Дили про это? (тк я говорю просто на опыте просмотра других скиллов и могу быть не права)

2023-06-19 15:32 UTC, smilni commented on skills/dff_api_skill/pipeline.yml
>      timeout: 10.0
ты же изменила его на 20

2023-06-19 15:35 UTC, smilni commented on skills/dff_api_skill/service_configs/dff-api-skill/service.yml
> +      ENVVARS_TO_SEND: OPENAI_API_KEY,GOOGLE_CSE_ID,GOOGLE_API_KEY
![Uploading Screenshot 2023-06-19 at 18.34.55.png…]()

2023-07-19 14:59 UTC, dilyararimovna commented
Improved and merged in https://github.com/deeppavlov/dream/pull/499

2023-07-19 14:59 UTC, closed without merging