Feat/skill selection llm
deeppavlov/dream pull request #486
Opened 2023-06-06 11:52 UTC by dilyararimovna

2023-06-26 13:13 UTC, Kpetyxova commented on assistant_dists/multiskill_ai_assistant/docker-compose.override.yml
> +        ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
Диля, а зачем нужен OPENAI_ORGANIZATION? без него же работает

2023-06-27 11:03 UTC, dilyararimovna commented on assistant_dists/multiskill_ai_assistant/docker-compose.override.yml
> +        ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
да просто до этого видела, что есть такой ключ, добавила. хз зачем

2023-06-27 15:56 UTC, Kpetyxova commented on assistant_dists/multiskill_ai_assistant/docker-compose.override.yml
> +        ENVVARS_TO_SEND: OPENAI_API_KEY,OPENAI_ORGANIZATION
надо его убрать отовсюдутогда

2023-06-27 15:56 UTC, Kpetyxova submitted a review, later dismissed

2023-06-27 23:43 UTC, smilni requested changes

2023-06-27 23:43 UTC, smilni commented on assistant_dists/multiskill_ai_assistant/docker-compose.override.yml
> +        GENERATIVE_SERVICE_URL: http://openai-api-davinci3:8131/respond
точно его, не чатпгт? просто если мы часто используем такой промпт-селектор, то давинчи в 10 раз дороже чем чатгпт, а по качеству вроде так же

2023-06-27 23:43 UTC, smilni commented on common/prompts/skill_selector.json
> +    "prompt": "Select N_SENTENCES_TO_RETURN the most relevant to the dialog context skills based on the given short descriptions of abilities of different skills of the assistant. Return only names o
Select N_SENTENCES_TO_RETURN skills most relevant to the dialog context based on the given short descriptions of abilities of different skills of the assistant. Return only the names of the selected skills divided by comma.\n\n

2023-06-27 23:43 UTC, smilni commented on annotators/prompt_selector/server.py
> +GENERATIVE_TIMEOUT = int(getenv("GENERATIVE_TIMEOUT", 5))
плюс пока я не подмержила дев ai_faq_assistant мне отвечал одним словом (явно обрезалось что-то у трансформеров). мердж свежего дева решил проблему, так что не стала вдаваться в подробности

2023-08-22 10:26 UTC, dilyararimovna commented
no more time to finish it.

2023-08-22 10:26 UTC, closed without merging