Move services to deeppavlov 1.1.1 and 1.2.0
deeppavlov/dream pull request #495
Opened 2023-06-20 08:56 UTC by NeoIsALie

Move some services from dev.yml to deeppavlov 1.1.1 and 1,2,0.

2023-06-27 07:35 UTC, dilyararimovna commented
![image](https://github.com/deeppavlov/dream/assets/14152126/a39305d8-4d25-42a9-b13a-55a13caeebb4)
fact-retrieval-ru не поднимается
http://dev.ipavlov.mipt.ru:8080/blue/rest/organizations/jenkins/pipelines/dream/branches/PR-495/runs/7/nodes/301/steps/306/log/?start=0

2023-06-28 11:14 UTC, IgnatovFedor requested changes
Коментарии к паре сервисов относятся и ко всем остальным

2023-06-28 11:14 UTC, IgnatovFedor commented on annotators/IntentCatcherTransformers/Dockerfile
> +RUN apt-get update && \
дважды в слое выполняется apt update, история с cuda потеряла смысл после обновления базового образа: нам приходилось выполнять apt-key del, wget cuda и т.п. только потому что мы юзали старый базовый образ.

На нижележащих слоях копируются и устанавливаются зависимости, большинство которых уже неактуально после обновления базового образа.

Плюс было бы хорошо перенести сервер на установленный в базовом образе flask, чтобы не ставить gunicorn, flask и всё что они тянут.

2023-06-28 11:14 UTC, IgnatovFedor commented on annotators/NER_deeppavlov/requirements.txt
> +deeppavlov==1.2.0
базовый образ уже содержит deeppavlov
Зависимости стоит отредактировать, учитывая новый базовый образ.

2023-06-28 11:14 UTC, IgnatovFedor commented on services/wiki_facts/Dockerfile
> +FROM deeppavlov/deeppavlov:1.1.1-gpu
Почему нельзя использовать одну вервию в deeppavlov в базовых образах?

2023-06-28 11:32 UTC, NeoIsALie commented on services/wiki_facts/Dockerfile
> +FROM deeppavlov/deeppavlov:1.1.1-gpu
В плане, почему везде не только 1.1.1 или только 1.2.0?

2023-06-30 07:19 UTC, NeoIsALie commented on services/wiki_facts/Dockerfile
> +FROM deeppavlov/deeppavlov:1.1.1-gpu
В некоторых образах при использовании версии 1.2.0 вылезают проблемы с конфигурациями моделей

2023-06-30 11:34 UTC, IgnatovFedor commented on annotators/fact_retrieval/requirements.txt
> +torch==1.7.1
Torch из базового образа совсем не совместим с моделью? Может можно обновить модель?

2023-06-30 12:20 UTC, NeoIsALie commented on annotators/fact_retrieval/requirements.txt
> +torch==1.7.1
Был несовместим, однако стоит поварьировать версию pytorch-lightning. Возможно, тогда будет совместим.

2023-06-30 13:32 UTC, NeoIsALie commented on annotators/fact_retrieval/requirements.txt
> +torch==1.7.1
Загвоздка была в версии `ligtning`. Исправлено в 37d94029391a3c2577045af79f30d4f168e3314d

2023-07-03 06:34 UTC, IgnatovFedor approved these changes

2023-07-03 06:35 UTC, merged