adding vicuna to available models
deeppavlov/dream pull request #496
Opened 2023-06-20 12:14 UTC by smilni

Ксюша / Диля, огромная просьба, проверьте внимательно порты и что нигде нет gptjt. Я проверила два раза, но могла запутаться, очень много изменений.

2023-06-20 13:34 UTC, dilyararimovna requested changes
еще в юниверсал промптед скилле добавь сразу в дикт ENVVARS_TO_SEND

2023-06-20 13:34 UTC, dilyararimovna commented on services/transformers_lm/server.py
> +from transformers import LlamaForCausalLM, LlamaTokenizer
это что

2023-06-20 13:34 UTC, dilyararimovna commented on services/transformers_lm/server.py
> +    "lmsys/vicuna-13b-v1.3": json.load(open("common/generative_configs/default_generative_config.json", "r")),
а вот это молодец!

2023-06-20 13:35 UTC, dilyararimovna commented
ну и в табличку MODELS.md

2023-06-20 13:35 UTC, smilni commented on services/transformers_lm/server.py
> +from transformers import LlamaForCausalLM, LlamaTokenizer
ой я не запушила коммит где убрала это

2023-06-30 10:23 UTC, dilyararimovna commented
I am closing this PR but do not delete the branch (for possible further usage when we will turn on vicuna)

2023-06-30 10:23 UTC, closed without merging