Fix/better llm response selector
deeppavlov/dream pull request #498
Opened 2023-06-21 09:42 UTC by smilni

2023-06-26 13:32 UTC, Kpetyxova submitted a review, later dismissed

2023-06-27 08:04 UTC, dilyararimovna requested changes

2023-06-27 08:04 UTC, dilyararimovna commented on common/generative_configs/generative_config_long.json
> +    "min_length": 8,
обнови конфиг

2023-06-27 12:38 UTC, dilyararimovna approved these changes

2023-06-27 12:41 UTC, merged