Add/reasoning and planning
deeppavlov/dream pull request #499
Opened 2023-06-23 09:15 UTC by Kpetyxova

skill with several API's that uses ChatGPT to think of actions and to choose what API is best to use

2023-06-28 06:51 UTC, dilyararimovna commented on assistant_dists/dream_reasoning/docker-compose.override.yml
> +        ENVVARS_TO_SEND: OPENAI_API_KEY,GOOGLE_CSE_ID,GOOGLE_API_KEY,OPENWEATHERMAP_API_KEY,NEWS_API_KEY,WOLFRAMALPHA_APP_ID
добавь инструкйию как их получать в виде ридми

2023-06-29 13:58 UTC, smilni reviewed
1. Неправильно сработал после собственного уточнения, как будто забыл вопрос:
You (цуащтьуамтьщзщзт): give me the news on topic: Macron
Bot:  To provide you with the most relevant news on Macron, could you please specify which aspect or event related to Macron you are interested in?
You (цуащтьуамтьщзщзт): anything recent
Bot:  Ukraine war: President Zelensky decries 'act of terror' as Russia missile strike kills eight in Kramatorsk
Paris: Macron calls police killing of teen 'unforgivable'
Ukraine war: Countdown has begun on Putin's end, say Kyiv officials
French police kill teen who refused traffic stop
South Koreans become a year younger under new age-counting law
Plan to slice New York pizza oven emissions by 75% causes backlash
Teen makes skateboarding history with 720 trick
Donald Trump countersues writer E Jean Carroll for defamation
Ex-NFL player Mallett, 35, dies in apparent drowning
Hajj: Price rises making pilgrimage increasingly unaffordable
Логи: https://pastebin.com/SvAbG22a

2. Просто упал без видимой причины, хотя в логах я вижу ответ.
User: why is the sky yellow?
Bot:  Hi, this is a Dream Socialbot! Anyway, Baking cookies is comforting, and cookies are the sweetest little bit of comfort food. They are very bite-sized and personal. Speaking of food, Do you think cooking is cool?

Логи: https://pastebin.com/NjxaTR3q

3. Опять упал. Таймаут? Не знаю. Мне вообще кажется таймаут нужен больше чем 30.
User: I need you to google 'how to take care after a parrot' for me.
Bot:  Sure, I'd be happy to help you with that. Before I search for information on taking care of a parrot, can you please clarify if you already have a parrot or if you are planning to get one? This will help me provide you with more specific and helpful information.
You (щшуцатщшкуптищшукптщ): I already have it
Bot:  I am a bit confused. What would you like to chat about?

Плюс судя по логам он не пошел в гугл и ответил сам несмотря на прямой запрос. Может опять детали поломали? Логи: https://pastebin.com/6ENUzBQY

2023-06-29 13:58 UTC, smilni commented on assistant_dists/dream_reasoning/pipeline_conf.json
> +        "description": "Version of DeepPavlov Dream Socialbot that uses resasoning and APIs to handle requests",
reasoning

2023-06-29 13:58 UTC, smilni commented on components/8XSyRJD0Rt.yml
> +    Skill uses ChatGPT to think which API is best to use and to form an input for it.
to decide

2023-06-29 13:58 UTC, smilni commented on components/8XSyRJD0Rt.yml
> +service: skills/dff_book_sfc_skill/service_configs/dff-reasoning-skill
dff_book_sfc_skill? О НЕТ УМОЛЯЮ ТОЛЬКО НЕ ОН

2023-06-29 13:58 UTC, smilni commented on skills/dff_reasoning_skill/component.yml
> +      ChatGPT is used to think what API is best to use and to form an input for it.
to decide / determine

2023-06-29 13:58 UTC, smilni commented on skills/dff_reasoning_skill/pipeline.yml
эти карточки разве нужны? нигде не вижу их

2023-06-29 13:58 UTC, smilni commented on skills/dff_reasoning_skill/component.yml
эти карточки разве нужны? нигде не вижу их

2023-06-29 13:58 UTC, smilni commented on skills/dff_reasoning_skill/scenario/condition.py
> +def is_last_utt_approval(ctx: Context, actor: Actor, *args, **kwargs) -> bool:
мелочь, но я бы заменила на bot_needs_approval или что-то такое. иначе читается как будто это функция которая проверяет на факт одобрения (положительного ответа)

2023-06-29 13:58 UTC, smilni commented on skills/dff_reasoning_skill/scenario/main.py
> +                "save_user_answer": loc_prc.save_user_answer(),
для понимания -- а зачем тут ответ сохраняется?

2023-06-29 13:58 UTC, smilni commented on skills/dff_reasoning_skill/scenario/main.py
> +            PROCESSING: {"set_is_final_answer_flag": is_final_answer.set_is_final_answer_flag(True)},
а почему тут финальный? мы же потом идем спрашивать можно ли использовать апи? я запуталась с флагами

2023-06-29 13:58 UTC, smilni commented on skills/dff_reasoning_skill/scenario/response.py
> +ANSWER ONLY YES/NO"""
у тебя указано что учитываем только 1 прошлое высказывание. а может быть такое, что детали были даны до этого?
- What's the weather in Moscow?
- Sunny, bla-bla-bla
- Will it rain today?

И боту придется уточнять, тк он же не увидит, что речь про Москву. Может все же N_UTTERANCES=3?

2023-06-29 13:58 UTC, smilni commented on skills/dff_reasoning_skill/scenario/response.py
> +DON'T EXPLAIN YOUR DECISION, JUST RETURN THE KEY. E.x. google_api"""
E.g.

2023-06-29 13:58 UTC, smilni commented on skills/dff_reasoning_skill/service_configs/dff-reasoning-skill/environment.yml
> +      N_UTTERANCES_CONTEXT: 3
один или три? по-разному в разных местах

2023-06-29 13:58 UTC, smilni commented on skills/dff_reasoning_skill/service_configs/dff-reasoning-skill/service.yml
у тебя опять одинаковые service и environment

2023-06-29 18:11 UTC, smilni commented on assistant_dists/dream_reasoning/pipeline_conf.json
> +        "description": "Version of DeepPavlov Dream Socialbot that uses resasoning and APIs to handle requests",
ну у тя resasoning

2023-06-29 18:12 UTC, smilni commented on skills/dff_reasoning_skill/scenario/main.py
> +            PROCESSING: {"set_is_final_answer_flag": is_final_answer.set_is_final_answer_flag(True)},
ааааа, блин, поняла

2023-06-29 18:18 UTC, Kpetyxova commented on assistant_dists/dream_reasoning/pipeline_conf.json
> +        "description": "Version of DeepPavlov Dream Socialbot that uses resasoning and APIs to handle requests",
ммм 😏😉😉😉

2023-07-03 09:21 UTC, dilyararimovna requested changes

2023-07-03 09:21 UTC, dilyararimovna commented on skills/dff_reasoning_skill/scenario/main.py
> +                "set_confidence": int_prs.set_confidence(1.0),
всем нодам везде конф=1? так не надо

2023-07-03 09:21 UTC, dilyararimovna commented on skills/dff_reasoning_skill/scenario/response.py
> +            GENERATIVE_SERVICE_URL,
pls сравни с тем, что в dff_prompted_skill, там по-другому уже сделано. используются функции специальные

2023-07-03 09:21 UTC, dilyararimovna commented on skills/dff_reasoning_skill/scenario/response.py
> +                "openai_api_keys": [sending_variables["OPENAI_API_KEY"]],
потому что не всем нужны ключи

2023-07-03 09:21 UTC, dilyararimovna commented on skills/dff_reasoning_skill/scenario/response.py
> +                GENERATIVE_SERVICE_URL,
тут тоже спец функции. вдруг не openai лмм

2023-07-03 09:21 UTC, dilyararimovna commented on skills/dff_reasoning_skill/scenario/response.py
> +                GENERATIVE_SERVICE_URL,
тут тоже

2023-07-03 09:21 UTC, dilyararimovna commented on skills/dff_reasoning_skill/scenario/response.py
> +                    "dialog_contexts": [dialog_context],
и тут!

2023-07-03 09:21 UTC, dilyararimovna commented on skills/dff_reasoning_skill/scenario/response.py
> +                GENERATIVE_SERVICE_URL,
и тут)

2023-07-03 09:30 UTC, Kpetyxova commented on assistant_dists/dream_reasoning/docker-compose.override.yml
> +        N_UTTERANCES_CONTEXT: 1
да, с бОльшим было плоха

2023-07-03 10:37 UTC, Kpetyxova commented on components/8XSyRJD0Rt.yml
> +  timeout: 150.0
а в докер компоузе GENERATIVE_TIMEOUT 

у скилла побольше

2023-07-03 10:38 UTC, Kpetyxova commented on skills/dff_reasoning_skill/Dockerfile
> +COPY ./skills/dff_weather_skill/data/ ./data/
присутствует

2023-07-05 08:23 UTC, dilyararimovna requested changes

2023-07-05 08:23 UTC, dilyararimovna commented on common/dff/integration/set_is_final_answer.py
> +    return update_is_final_answer
I suggest to move it to common/dff/integration/processing.py

2023-07-05 08:23 UTC, dilyararimovna commented on services/agent_services/service_configs/dream_reasoning/environment.yml
> +LANGUAGE: EN
строчку про фоллбек файл

2023-07-05 08:23 UTC, dilyararimovna commented on services/agent_services/service_configs/dream_reasoning/service.yml
> +    LANGUAGE: EN
строку про фоллбек файл

2023-07-05 08:23 UTC, dilyararimovna commented on skills/dff_reasoning_skill/api_configs/api_conf.json
> +        "timeout": 30.0,
таймауты появились - класс! только их еще заиспользвоать надо в скилле))

2023-07-06 19:43 UTC, dilyararimovna requested changes

2023-07-06 19:43 UTC, dilyararimovna commented on skills/dff_reasoning_skill/scenario/response.py
> +    "wolframalpha_api": wolframalpha_response,
одна просьба, я только щас этот маппинг заметила. 
Мне кажется, заставить человека пистаь маппинг еще - можно забыть об этом случайно. предлагаю по умолчанию считать, что функция должна называться
f"{api_name}_response"

2023-07-07 15:21 UTC, merged