Feat/add external integration skill
deeppavlov/dream pull request #504
Opened 2023-06-28 14:46 UTC by smilni

2023-07-03 06:52 UTC, NeoIsALie requested changes

2023-07-03 06:52 UTC, NeoIsALie commented on skills/external_integration_skill/Dockerfile
> +FROM python:3.7.4
Мч используем новые версии python, 3.9, 3.10. Поменяй версию на одну из представленных.

2023-07-03 06:52 UTC, NeoIsALie commented on skills/external_integration_skill/test.py
> +
Добавь еще один тест, где он возвращает тебе пустой ответ и нулевой `confidence`.

2023-07-03 13:54 UTC, dilyararimovna requested changes

2023-07-03 13:54 UTC, dilyararimovna commented on skills/external_integration_skill/server.py
> +                "dialog_id": dialog_id,
меня только смущает, что мы шлем наш айдишник диалога. а не айдишник пользователя - мне не понятно, что лучше слать.

2023-07-03 13:54 UTC, dilyararimovna commented on skills/external_integration_skill/server.py
> +            response = result.get(RESPONSE_KEY, "")
мы же говорили, что надов се случаи предусмотреть. если например в result уже лежит просто строка? без ключа?

2023-07-03 13:54 UTC, dilyararimovna commented on skills/external_integration_skill/server.py
> +            confidence = result.get("confidence", 0.0)
ну и смысл такое дефолтное значение делать - все гипотезы с конф=0 будут дропаться агентом автоматически.
сделай 0.9 например

2023-07-03 13:54 UTC, dilyararimovna commented on skills/external_integration_skill/server.py
> +            logger.info(f"Response: {str(response)}, confidence: {str(confidence)}")
тут логгируешь, потом еще ниже логгируешь. зачем два раза. пусть будет один раз в концуе, а это убрать

2023-07-03 16:56 UTC, smilni commented on skills/external_integration_skill/server.py
> +            confidence = result.get("confidence", 0.0)
у нас в хороших случаях, когда она досталась, 0.9. я решила что если не досталось то что-то не так, поэтому 0 поставила. можем 0.8 например?

2023-07-03 16:58 UTC, smilni commented on skills/external_integration_skill/server.py
> +            response = result.get(RESPONSE_KEY, "")
предполагаем что что в таком случае передано в RESPONSE_KEY? None? или его вообще нет? или это не по нему проверять, а по result-у, что он не строка?

2023-07-03 16:58 UTC, smilni commented on skills/external_integration_skill/server.py
> +            logger.info(f"Response: {str(response)}, confidence: {str(confidence)}")
очень люблю логгировать. уберу)

2023-07-04 07:56 UTC, smilni commented on skills/external_integration_skill/server.py
> +                "dialog_id": dialog_id,
передаем тоже как параметр

2023-08-06 10:58 UTC, dilyararimovna requested changes

2023-08-06 10:58 UTC, dilyararimovna commented on skills/external_integration_skill/server.py
> +    PAYLOAD_ARGUMENT_NAME = "payload"
PAYLOAD_ARGUMENT_NAME = getenv("PAYLOAD_ARGUMENT_NAME", "payload")

2023-08-06 10:58 UTC, dilyararimovna commented on skills/external_integration_skill/server.py
> +    PAYLOAD_ARGUMENT_NAME = "payload"
etc

2023-08-06 10:58 UTC, dilyararimovna commented on skills/external_integration_skill/server.py
> +assert "EXTERNAL_SKILL_URL", logger.info("You need to provide the external skill url to get its responses.")
probably it is better to raise logger.error

2023-08-06 10:58 UTC, dilyararimovna commented on skills/external_integration_skill/server.py
> +        logger.info(f"Responses: {str(responses)}, confidences: {str(confidences)}")
those logs are will be repeated for every element of the batch

2023-08-06 10:58 UTC, dilyararimovna commented on skills/external_integration_skill/service_configs/external-integration-skill/service.yml
> +      REQUEST_TIMEOUT: 10
параметры здесь не соответствуют тем, что в карточке в environment.yml

2023-08-06 10:58 UTC, dilyararimovna commented on skills/external_integration_skill/service_configs/external-integration-skill/service.yml
> +  command: gunicorn --workers=1 server:app -b 0.0.0.0:$8183 --timeout=300
$ лишний!

2023-08-15 11:31 UTC, merged