Key components readmes
deeppavlov/dream pull request #510
Opened 2023-07-06 13:14 UTC by nstsj

Currently all readmes are build according to this template:
__________
# Component Name

## Description

component_type: *add here*
is_customizable: true/false *(choose one, pls)*

*text for short description here*

## I/O
*text here if i/o specified*

## Dependencies

Configuration settings specified in the .yaml files at [service_configs](link)

Required Python packages specified in [requirements.txt](link).

For more details on inner workings of the component please refer to [server.py](link)
__________

Things to correct/improve: 
- overall readme format for desired points to include there. 
- I/O info on some components (where not specified)

2023-07-06 19:47 UTC, dilyararimovna commented on annotators/BadlistedWordsDetector/README.md
> +output: json dict
вообще не про typing же это поле, а про смысл - что в этом дикте лежит

2023-07-06 19:47 UTC, dilyararimovna requested changes

2023-07-06 19:47 UTC, dilyararimovna commented on annotators/BadlistedWordsDetector/README.md
> +is_customizable: true
4 и 5 строки  - это можно не писать

2023-07-06 19:47 UTC, dilyararimovna commented on annotators/BadlistedWordsDetector/README.md
> +For more details please refer to [this script](server.py)
тут имелось в виду, зависит ли от других компонентов в пайплайне.

2023-07-08 23:10 UTC, closed without merging

2023-07-08 23:11 UTC, nstsj commented
PR closed bc it was a test one, we'll re-write readmes