Fromage annotator and dff-fromage-image-skill
deeppavlov/dream pull request #523
Opened 2023-07-11 19:03 UTC by ciwwwnd

Все, что относится к fromage аннотатору: 

`/dp-formatters: `
* получаем список из пяти последних вхождений картинок (если есть картинка, то путь к ней, если нет картинки, то None). Выглядит это примерно так `[None, 'https://bla-bla', None, None, 'https://bla-bla']`. 
* Если сообщение текстовое — вытаскиваем последнее сообщение и среди полученного списка с адресами картинок вытаскиваем последний адрес к картинке, который не None и начинается с http
* Если получаем картинку сразу, то вытаскиваем адрес к картинке и поле text оставляем пустой строкой

Почему пустой строкой? Переходим к `server.py` аннотатора. 

Если поле текст — пустая строка, мы автоматически отправляем во фромаж последнюю пикчу и запрос ‘What is the image?’, чтобы он выдал релевантную информацию к картинке, а не просто последнее обсуждавшееся сообщение. 

Можем обсуждать картинку примерно 5 сообщений (из-за устройства форматтера)

Что может работать не так: 
* после 5 сообщений может крашится из-за break в цикле, если не получает новую картинку (потому что тогда список состоит только из None)
* может выдавать невнятные ответы типа A:A:A:A: и прочие вещи. Это ок, он сам по себе такой. 

Скилл:

Просто выдает аннотацию фромажа. Там есть невнятный переход (condition, который всегда возвращает True), который не несет смысловой нагрузки, но возможно там будут нормальные переходы когда-нибудь между нодами… 

Запуск: 

`docker-compose -f docker-compose.yml -f assistant_dists/dream_multimodal/docker-compose.override.yml -f assistant_dists/dream_multimodal/dev.yml -f assistant_dists/dream_multimodal/proxy.yml up --build 
`

`docker-compose exec agent python -m deeppavlov_agent.run agent.channel=telegram agent.telegram_token=<INSERT_YOUR_TG_TOKEN_HERE> agent.pipeline_config=assistant_dists/dream_multimodal/pipeline_conf.json`

![Screenshot 2023-07-13 at 13 10 38](https://github.com/deeppavlov/dream/assets/63125509/e754a35e-b634-4c38-b9da-6f99b1ca2815)

2023-07-12 09:41 UTC, oserikov commented
@ciwwwnd please, fix black/flake8 errors

2023-07-26 08:53 UTC, smilni requested changes
вроде всё, по любым вопросам пиши нам в тред или отвечай тут на комменты)
единственное -- я пока его не поднимала и не говорила, когда поправишь архитектурно и по коду, пингани меня, я еще раз по всему пройдусь, и уже тогда с ним пообщаюсь

2023-07-26 08:53 UTC, smilni commented on assistant_dists/dream_multimodal/docker-compose.override.yml
> +  fromage:
мы с Дилей посовещались и решили, что нужно переделать архитектуру -- пусть у тебя будет сервис (а не аннотатор) фромаж, и его будет использовать image-captioning вместо того, что там используется сейчас. это будет логичнее и полезнее, чем делать отдельный скилл с кэпшнами, когда в дистрибутиве есть image-captioning, просто видимо устаревший.

2023-07-26 08:53 UTC, smilni commented on annotators/fromage/fromage/__init__.py
меня очень смущает эта папка. если это чисто скопированный чужой код, так делать ни в коем случае нельзя, даже если у них всё-позволяющая лицензия. сделай, пожалуйста, так, чтобы он скачивался или импортировался

2023-07-31 03:16 UTC, ciwwwnd commented on assistant_dists/dream_multimodal/docker-compose.override.yml
> +  fromage:
вопрос, а если это сервис, то state_manager_method будет add_annotation или как у скиллов add_hypothesis?

2023-07-31 04:09 UTC, ciwwwnd commented on annotators/fromage/fromage/__init__.py
пофикшено, импортируется при подгрузке контейнера, но если что контейнер оч долго билдится

2023-07-31 04:11 UTC, ciwwwnd commented on annotators/fromage/fromage/__init__.py
единственная проблема, которая осталась -- таймауты, я в коде оставила cuda_visible_devices = 0, но вообще чтобы в таймауты укладываться нужно всю а100 использовать, но в логи результаты фромажа попадают и можно видеть результаты работы скилла и сервиса

а так вообще в терминал падает вот эта штука, но у фромажа скорость ответов от 2 секунд до 45 секунд, непонятно какие таймауты тогда ставить.... вот с этим правда не знаю, что делать 

`(TimeoutError(), {'payload': {'task_id': '319945a3555c48e593b382a901fd0682', 'payload': {'sentences': ['What is the name of the plant?'], 'image_paths': ['http://files:3000/file?file=ee25e7b753764e37baea80dbbaec1beb.jpg']}}, 'url': 'http://fromage:8069/respond'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/deeppavlov_agent/core/connectors.py", line 24, in send
    async with self.session.post(self.url, json=payload["payload"], timeout=self.timeout) as resp:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/usr/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError`

2023-07-31 09:54 UTC, smilni commented on assistant_dists/dream_multimodal/docker-compose.override.yml
> +  fromage:
сервисы вообще не прописываются в pipeline_conf, только аннотаторы, которые к ним обращаются

2023-07-31 09:55 UTC, ciwwwnd commented on assistant_dists/dream_multimodal/docker-compose.override.yml
> +  fromage:
поняла, щас пофикшу!

2023-07-31 09:56 UTC, smilni commented on annotators/fromage/fromage/__init__.py
долго билдится -- не страшно)
а зачем тебе укладываться в таймауты? ты можешь их сама установить как тебе нужно. ты пишешь скорость ответа от 2 до 45 секунд, а почему такой разборм, от чего зависит?

2023-07-31 09:58 UTC, ciwwwnd commented on annotators/fromage/fromage/__init__.py
хехехех, я просто помню, что когда делала имадж скилл Диля просила потом вернуть таймауты на минимальные, поэтому они щас по дефолту стоят маленькие.... 

от количества карточек зависит, на 4х отвечает быстрее, чем на одной, поэтому я и запуталась какие ставить...

2023-07-31 10:00 UTC, smilni commented on annotators/fromage/fromage/__init__.py
ааа, я поняла. а сейчас он должен уложиться на 1 карточку или на 4? какие у тебя требования были от Олега/Дили/кого-то еще?

2023-07-31 10:00 UTC, smilni commented on annotators/fromage/fromage/__init__.py
таймауты должны быть минимально возможные, да. но если ответ ждать 45 секунд, то что поделаешь, тогда минимально возможный таймаут это 45 секунд...

2023-07-31 10:05 UTC, smilni commented on annotators/fromage/fromage/__init__.py
ну вообще да, стараемся с cuda_visible_device = 0 
Олег про количество карточек не говорил, верно? я тогда сегодня у Дили спрошу и пришлю тебе ответ

2023-07-31 10:05 UTC, smilni commented on annotators/fromage/fromage/__init__.py
просто можно и так и так, зависит от того хочешь ты быстро и много ресурсов или медленно и мало))

2023-07-31 10:06 UTC, ciwwwnd commented on annotators/fromage/fromage/__init__.py
неа, не говорил! буду ждать тогда, спасибо!!

2023-07-31 16:16 UTC, smilni commented on annotators/fromage/fromage/__init__.py
пока не было возможности поговорить с Дилей, увеличь просто их пока пожалуйста, чтоб я его смогла поднять и чтоб он работал
как поговорю сразу отпишусь

2023-07-31 16:18 UTC, smilni commented
Нелля, у тебя еще почему-то после правок в изменениях появилось 360 файлов :О Из них большинству никак не относятся к фромажу
Разберись пожалуйста с этим, убери все, что не твое

2023-08-01 06:45 UTC, smilni commented on annotators/fromage/fromage/__init__.py
сделать test.yml и test_4.yml. по умолчанию пусть будет на одной карте (в докер-компойз ямле например).
а в test_4.yml можешь сделать 4 штуки, и когда тебе надо запустить на 4 карточка, просто в команду добавляй -f .../test_4.yml

2023-08-02 20:06 UTC, smilni commented
Нелля, все еще лишние файлы 😢 Навскидку 4 из 5 папок тут не твои и их не должно быть в твоем пр
<img width="225" alt="Screenshot 2023-08-02 at 23 05 37" src="https://github.com/deeppavlov/dream/assets/42929200/64d00744-968c-4e5b-81c3-e8352a1df6c7">

2023-08-03 19:53 UTC, smilni commented on assistant_dists/dream_multimodal/docker-compose.override.yml
> -  dff-program-y-skill:
менять ничего не надо, на будущее -- лучше было бы оставить его как есть, а вот ненужный convers-evaluation-selector заменить на нужный ranking-based-response-selector. а так сложно логику изменений понять просто

2023-08-03 19:54 UTC, smilni commented on assistant_dists/dream_multimodal/dev.yml
> -  convers-evaluation-selector:
а добавить вместо него ranking-based?

2023-08-03 19:58 UTC, smilni commented on components/8iHHdjsnfhewkl.yml
> +gpu_usage: 5G
слушай, а точно не больше? ты проверила? авторы вот что утверждают
<img width="792" alt="Screenshot 2023-08-03 at 22 58 13" src="https://github.com/deeppavlov/dream/assets/42929200/6d244528-5838-426a-9c08-7019a63996c7">

2023-08-03 19:59 UTC, smilni commented on components/8jfFjmYnbdeH.yml
> +ram_usage: 1024M
уверена что так много? проверила docker stats?

2023-08-03 19:59 UTC, smilni commented on components/8jfFjmYnbdeH.yml
> +ram_usage: 1024M
обычно у скиллов меньше

2023-08-03 19:59 UTC, smilni commented on services/fromage/pipeline.yml
> +    timeout: 3.0
?

2023-08-03 20:00 UTC, smilni commented on skills/dff_fromage_image_skill/component.yml
Нелль, мы вроде убрали component.yml файлы. извини, очень часто все меняется. посмотри пожалуйста свежий дев и сделай по аналогии ровно как в нем

2023-08-03 20:01 UTC, smilni commented on skills/dff_fromage_image_skill/component.yml
чтоб лишнего не было а нужное было

2023-08-03 20:01 UTC, smilni commented on skills/dff_fromage_image_skill/component.yml
и pipeline.yml вроде тоже

2023-08-03 20:04 UTC, smilni commented on skills/dff_fromage_image_skill/scenario/condition.py
> +    caption = int_ctx.get_last_human_utterance(ctx, actor).get("annotations", {}).get("fromage", {})
не вижу изменений хотя вижу что вроде во фромаже лежит строка. нет?

2023-08-03 20:05 UTC, smilni commented on skills/dff_template_prompted_skill/service_configs/dff-informal-letter-ru-prompted-skill/environment.yml
это не твое

2023-08-03 20:05 UTC, smilni commented on skills/dff_template_prompted_skill/service_configs/dff-official-letter-ru-prompted-skill/environment.yml
это не твое

2023-08-03 20:08 UTC, smilni commented on services/agent_services/service_configs/dream_multimodal/environment.yml
>  WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-480}
<img width="899" alt="Screenshot 2023-08-03 at 23 07 57" src="https://github.com/deeppavlov/dream/assets/42929200/b5c6ca03-af8d-4fdc-84c0-977999e9087f">

2023-08-03 20:08 UTC, smilni commented on services/agent_services/service_configs/dream_multimodal/environment.yml
>  WAIT_HOSTS_TIMEOUT: ${WAIT_TIMEOUT:-480}
таймаут

2023-08-03 20:10 UTC, smilni commented on services/fromage/README.md
> +**FROMAGe** is a service that is used to get an image and respond accordingly to the user's questions. FROMAGe is based on grounding pretrained language models to the visual domain ([Grounding Langua
**FROMAGe** is a service that is used to process an input image and respond to the user's questions accordingly. It is based on the [FROMAGe](https://github.com/kohjingyu/fromage/tree/main) model from [Grounding Language Models to Images for Multimodal Inputs and Outputs](https://arxiv.org/abs/2301.13823).

2023-08-03 20:10 UTC, smilni commented on services/fromage/README.md
> +GPU RAM 5 GB, RAM 5 GiB.
GB not GiB

2023-08-03 20:14 UTC, smilni commented on services/fromage/server.py
> +            for sentence in sentences:
`for image_path, sentence in zip(image_paths, sentences):`

иначе у тебя выходит что в ситуации path_1, path_2 + sentence_1, sentence_2 ты пройдешь по 4 вариантам вместо двух (path_1 sentence_1, path_1 sentence_2, path_2 sentence_1, path_2 sentence_2 а надо просто path_1 sentence_1, path_2 sentence_2)

2023-08-03 20:16 UTC, smilni commented on services/fromage/server.py
> +RET_SCALE_FACTOR = 0
я бы вынесла его во внешние аргументы. но это на подумать, хочешь ты всегда его нулем иметь, или иметь возможность задавать его прямо в аргах в docker-compose.override.yml. я за второе, потому что вы же планируете расширять фромаж, и возможно для других ситуаций нужен будет другой RET_SCALE_FACTOR

2023-08-03 20:18 UTC, smilni commented on services/fromage/server.py
> +def generate_responses(image_path, prompt, RET_SCALE_FACTOR):
не обязательно подавать RET_SCALE_FACTOR аргументом в функцию, он же у тебя константа, задаваемая в начале файла, и и так будет виден внутри функций

2023-08-04 07:53 UTC, smilni commented on assistant_dists/dream_multimodal/docker-compose.override.yml
> +  fromage:
Нелля, сейчас оставь, но на будущее. Тебе может потребоваться использовать фромаж как сервис, не записывая никуда его аннотацию. Например можно прям в самом скилле где-то внутри функции response залезть в фромаж и достать ответ. В таком случае ты вообще не пишешь его в pipeline_conf, и переделываешь эндпойнт немного (можешь для примера посмотреть [openai_api_lm](https://github.com/deeppavlov/dream/tree/main/services/openai_api_lm), [transformers_lm](https://github.com/deeppavlov/dream/tree/main/services/transformers_lm) и сделать так же. Мы вообще хотели, чтоб ты и тут так сделала 😅 Но уже ладно, так тоже норм, главное работает!

2023-08-04 08:36 UTC, dilyararimovna requested changes
- вернуть удаленные файлы про informal letter из skills/dff_template_prompted_skill
- в описании пр есть про "крашится в таких-то случаях", надо понимать, что каждый раз, как компонента крашится с ошибкой, она переподнимается! а это в случае больших нн моделей занимает прилично времени. Поэтому надо избежать всех возможных крашей с помощью try-except или правильных дефолтных значений

2023-08-04 08:36 UTC, dilyararimovna commented on assistant_dists/dream_multimodal/test_4.yml
> +      - 8012:8012
same as for test.yml

2023-08-04 08:36 UTC, dilyararimovna commented on services/agent_services/service_configs/dream_multimodal/environment.yml
> +WAIT_HOSTS: spelling-preprocessing:8074, sentseg:8011, badlisted-words:8018, intent-catcher:8014,
проверь список, тут есть спелл чек, который ты вроде выпилила

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/Dockerfile
> +RUN pip install fromage
почему версия не зафиксирована?

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/Dockerfile
> +RUN pip install gdown
почему версия не зафикисирована?

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/README.md
> +sudo AGENT_PORT=4242 docker-compose -f docker-compose.yml -f assistant_dists/dream/docker-compose.override.yml -f assistant_dists/dream/dev.yml -f assistant_dists/dream/test.yml up --build fromage
dream_multimodal 3 times in a command

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/server.py
> +RET_SCALE_FACTOR = int(os.getenv("RET_SCALE_FACTOR"))
перенести в билд арги и добавить в dockerfile прокидывание в энв

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/server.py
> +    logger.info(f"sentence {sentences}")
those  two prints are extra logs I suppose

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/server.py
> +    logger.info(f"prompt generate responses {prompt}")
this one is unneccassary log because of the 43th line

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/server.py
> +    logger.info(f"prompts {prompt}")
so here it's better to print both image path and a question (in one line, to be consistent in logs )

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/server.py
> +        text += f"Q: {p}\nA:"
if fromage is more about question, so maybe it's better to work with it only if there is some question in the utterance?

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/server.py
> +        text += f"Q: {p}\nA:"
in common.universal_templates we have is_any_question_sentence_in_utterance

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/server.py
> +    for p in prompt:
does this means you may have several prompts in the same utterance? what if the sentence is a string, then you will iterate over letters. or sentence is a list?

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/server.py
> +        text += " ".join([s for s in model_outputs if isinstance(s, str)]) + "\n"
i do not clearly understand what are you doing. every time you iterate over the previous utterances in the dialog?

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/server.py
> +        logging.info(f"frmg_answers here {frmg_answers}")
this is a non beautiful log. If you decided to log one by one, so move the log of the answer inside the function above

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/server.py
> +        frmg_answers = [[""]] * len(sentence)
the batch is sentences not sentence

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/service_configs/fromage/environment.yml
> +FLASK_APP: server
do not forget to add here the parameter from build args which is going to be added there

2023-08-04 08:36 UTC, dilyararimovna commented on services/fromage/service_configs/fromage/service.yml
> +        memory: 5G
this is another value. in docker-compose.override.yml you have 18G

2023-08-04 08:36 UTC, dilyararimovna commented on skill_selectors/rule_based_selector/connector.py
> +                skills_for_uttr.append("dff_fromage_image_skill")
а если картинка была в предыдущей реплике и в текущую не попала, то и скилл не будет включаться? ты же вроде хотела, чтобы он мог до 5 реплик после присланной картинки обсуждать.

2023-08-04 08:36 UTC, dilyararimovna commented on state_formatters/dp_formatters.py
> +        d.update({"sentences": [dialog["human_utterances"][-1]["text"]]})
мне больше импонирует вариант
```
human_text_uttr = dialog["human_utterances"][-1]["text"]
d = {"sentences":  [human_text_uttr if human_text_uttr else ""]}}
```
потому что в твоем варианте проверки выглядят не понятно для стороннего человека

2023-08-04 08:36 UTC, dilyararimovna commented on state_formatters/dp_formatters.py
> +                d.update({"image_paths": [url]})
то есть в принципе у тебя в итоге может вообще не оказаться в d ключа image_paths, что не хорошо. Надо поправить.

2023-08-04 08:36 UTC, dilyararimovna commented on state_formatters/dp_formatters.py
> +        d.update({"sentences": [""]})
когда выполняется этот кусок? когда в human uttr последнем пусто? если грамотно переделать предыдущий кусок, то этот не понадобится.

2023-08-04 08:36 UTC, dilyararimovna commented on state_formatters/dp_formatters.py
> +        d.update({"sentences": [""]})
и вообще однобуквенные переменные - это плохой тон, заменить d на input_dict или подобное

2023-08-04 08:36 UTC, dilyararimovna commented on components/8iHHdjsnfhewkl.yml
> +gpu_usage: 18G
в docker-compose.override.yml прописывается память не на гпу, а оперативка. ПОправить на корректные значения везде. Причем эти значения в docker-compose.override.yml  - это прям лимит, то есть контейнер будет переподниматься, так как превзошел лимиты по оперативке. Так что назначай ее в виде максимального значения (например, при подгрузке модели на гпу скорее всего оперативы будет кушаться много)

2023-08-04 08:46 UTC, smilni commented on skills/dff_template_prompted_skill/service_configs/dff-informal-letter-ru-prompted-skill/environment.yml
ой, да, я имела в виду не удалить прям под ноль, а вернуть к виду дева) чтоб он не показывался в твоих изменениях

2023-08-04 09:52 UTC, ciwwwnd commented on services/fromage/server.py
> +        text += " ".join([s for s in model_outputs if isinstance(s, str)]) + "\n"
неа, он итерируется по аутпутам, который получает от generate_for_images_and_texts, а так использую только последнее текстовое вхождение

просто generate_for_images_and_tests пикчи тоже может генерить

2023-08-04 11:54 UTC, ciwwwnd commented on services/fromage/server.py
> +        text += f"Q: {p}\nA:"
ну он просто болтать про картинку умеет тоже и абстрактно без вопросов от юзера (но вообще функционально он как dialogpt + картинка), говорить что цветы привез из средиземноморья...  поэтому я так оставила

2023-08-04 12:24 UTC, dilyararimovna requested changes

2023-08-04 12:24 UTC, dilyararimovna commented on assistant_dists/dream_multimodal/pipeline_conf.json
> -            "spelling_preprocessing": {
кстати мало просто удалить его, по всему пайплайн конф посмотри - аннотаторы ждут спеллинг, и в итоге не запустятся(

2023-08-04 12:24 UTC, dilyararimovna commented on assistant_dists/dream_multimodal/pipeline_conf.json
> +                    "service": "skill_selectors/description_based_skill_selector/service_configs/agent"
почему используется description based skill selector, а добавляется он в rule based selector

2023-08-04 12:32 UTC, ciwwwnd commented on assistant_dists/dream_multimodal/pipeline_conf.json
> +                    "service": "skill_selectors/description_based_skill_selector/service_configs/agent"
так вроде щас description based skill selector как в деве дрима основного, или нет? я запуталась

вернуть rule_based? я вроде везде его выпилила и по поиску в папке вроде ничего на него не похоже
или он не туда встал?

2023-08-04 12:51 UTC, dilyararimovna commented on assistant_dists/dream_multimodal/pipeline_conf.json
> +                    "service": "skill_selectors/description_based_skill_selector/service_configs/agent"
да,в ерни rule based skill selector

2023-08-06 07:05 UTC, dilyararimovna requested changes

2023-08-06 07:05 UTC, dilyararimovna commented on skill_selectors/rule_based_selector/connector.py
> +                skills_for_uttr.append("dff_fromage_image_skill")
ты хочешь во всех случаях включать скилл? странная логика. Надо делать так: включать 5 реплик после присланной картинки

2023-08-06 13:05 UTC, ciwwwnd commented on state_formatters/dp_formatters.py
> +    for url in reversed(image_paths):
а почему самую далеко находящуюся? ситуация же такая: пользователь отправляет картинку (это url), дальше пишет текстовые вопросы (и тогда вместо url каждый раз будет последовательно None)
то есть url - None - None - url - None - None, мы тогда список переворачиваем и вытаскиваем самый последний url

2023-08-08 08:17 UTC, dilyararimovna requested changes

2023-08-08 08:17 UTC, dilyararimovna commented on skill_selectors/rule_based_selector/connector.py
> +                    skills_for_uttr.append("dff_fromage_image_skill")
ты включаешь скилл в итоге в 5 пяти репликах диалога, елси есть картинка. По-моему ты хочешь по-другому.
Тебе надо чекнуть, есть ли в последних пяти репликах от человека картинка. Если есть, то включить твой скилл.

2023-08-08 08:17 UTC, dilyararimovna commented on state_formatters/dp_formatters.py
> +    for url in reversed(image_paths):
ну у тебя брейка нет, ты переворачиваешь лист (то есть он становится с последней реплики до -5), начинаешь идти по листу и обновляешь input_dict. Ну и будешь обновлять его до самой -5 реплики, потому что break-то у тебя нет!

2023-08-22 11:06 UTC, dilyararimovna requested changes

2023-08-29 06:17 UTC, oserikov commented
@dilyararimovna @smilni PR moved to #562 .

2023-08-29 06:17 UTC, closed without merging