Feat/ruxglm prompted dist
deeppavlov/dream pull request #528
Opened 2023-07-18 07:45 UTC by dilyararimovna

2023-07-18 16:57 UTC, smilni requested changes
**dream_persona_ruxglm_prompted** 
лишний AI откуда-то. исходя из [логов](https://pastebin.com/MC05Ae5r) модель так и генерит. но плохо, что выбралась гипотеза, которой верно присвоен низкий конфиденс (0.7) из-за отсутствия знака препинания в конце, хотя была норм гипотеза с 0.9. мб стоит ставить 0.5 если нет точки, чтоб сильнее вклад был

<img width="941" alt="Screenshot 2023-07-18 at 19 35 46" src="https://github.com/deeppavlov/dream/assets/42929200/13cfd016-97f8-44d0-b5ee-124f146e7f85">

это не пофиксить наверное, но иногда просто повторяет промпт. может можно предусмотреть и давать нулевой конфиденс за такое
<img width="1048" alt="Screenshot 2023-07-18 at 19 38 29" src="https://github.com/deeppavlov/dream/assets/42929200/a9c7b3ab-56e2-4f74-aa1c-4bb427ea42c2">

видимо моделька слишком маленькая, чтоб нормально следовать большому промпту. я бы подумала над тем чтоб урезать промпт раз в пять, пусть там совсем немного будет, но она хоть слушаться будет. а то четко прописан любимый фильм, но ответ вот: 
<img width="1039" alt="Screenshot 2023-07-18 at 19 45 24" src="https://github.com/deeppavlov/dream/assets/42929200/4a7b0256-4f87-4957-8aaa-c8a14304a1f6">

**dream_persona_rullama_prompted** 
нет proxy.yml. локально ничего не поднимается, ллама из-за отсутствия scipy, диалогрт из-за (вроде) нехватки памяти: [логи](https://pastebin.com/f6jUVE1m)

2023-07-18 16:57 UTC, smilni commented on components/dfagno94ntl23rbj.yml
> +  service (among the considered) to generate a response.
непонятно что имеется в виду (among the considered)

2023-07-18 16:57 UTC, smilni commented on components/dfjkgnhadoik4utfnaksdf.yml
> +description: A private large language model which was fine-tuned
A private large language model for the Russian language
а то самого важного нет)

2023-07-20 11:42 UTC, smilni commented on assistant_dists/universal_ru_prompted_assistant/docker-compose.override.yml
> +        DEFAULT_LM_SERVICE_URL: http://transformers-lm-oasst12b:8158/respond
так и должно быть, open assistant для русского?

2023-07-20 11:42 UTC, smilni commented on components/dfagno94ntl23rbj.yml
> +description: Universal prompt-based skill which accepts a prompt, a language modelling
ок, что не на русском?

2023-07-20 11:42 UTC, smilni commented on components/dfjkgnhadoik4utfnaksdf.yml
> +description: A private large language model for the Russian language which was fine-tuned
ок, что не на русском?

2023-07-20 11:42 UTC, smilni commented on services/transformers_lm/service_configs/transformers-lm-ruxglm/service.yml
> +  - .env_secret
разве нужен секрет?

2023-07-27 10:29 UTC, dilyararimovna commented on assistant_dists/universal_ru_prompted_assistant/docker-compose.override.yml
> +        DEFAULT_LM_SERVICE_URL: http://transformers-lm-oasst12b:8158/respond
fixed!

2023-07-27 14:12 UTC, merged