Models table upd
deeppavlov/dream pull request #539
Opened 2023-07-28 15:21 UTC by nstsj

2023-07-28 17:58 UTC, smilni commented
что тут случилось с историей коммитов? так лучше не делать

2023-07-30 10:28 UTC, nstsj commented
да, я подтянула себе свежий дев и вмержила его в эту ветку, так подъехали множественные коммиты из дева. 
Я сделала merge,  потому что при ребейзе приходилось разрешать конфликты в версиях файлах в каждом отдельном коммите, таким образов один и тот же файл иногда приходилось проверять несколько раз. 

Какой у нас best practice при подтягивании дева? Чтобы я в будущем делала так, как мы делаем

2023-07-31 16:05 UTC, smilni commented on MODELS.md
> +|--|--|--|--|--|--|--|--|
как Диля сказала, поправь плиз файл визуально, чтоб он был читаемый и в маркдауне

2023-07-31 16:06 UTC, smilni commented on MODELS.md
> +|[Anthropic Claude-v1](https://docs.anthropic.com/claude/reference/complete_post)|anthropic-api-claude-v1|no|supposedly, 52B| - (cannot be run locally) |9,000 tokens|available under subscription plan
а куда исчезло его описание и три модели после него? это специально удалено или случайно потерлось?

2023-07-31 17:09 UTC, nstsj commented on MODELS.md
> +|[Anthropic Claude-v1](https://docs.anthropic.com/claude/reference/complete_post)|anthropic-api-claude-v1|no|supposedly, 52B| - (cannot be run locally) |9,000 tokens|available under subscription plan
айй, случайно потерлось, я поправлю

2023-08-01 11:24 UTC, dilyararimovna requested changes
переделайте в читаемую таблицу, как раньше было (отступы колонки)

2023-08-06 07:49 UTC, dilyararimovna approved these changes

2023-08-06 07:49 UTC, merged