Feat/prompted robot
deeppavlov/dream pull request #550
Opened 2023-08-08 11:51 UTC by smilni

2023-08-08 12:39 UTC, dilyararimovna requested changes

2023-08-08 12:39 UTC, dilyararimovna commented on assistant_dists/dream_robot_prompted/dev.yml
> +      - 8176:8176
проверь порты - они в разных файлах различаются

2023-08-08 12:40 UTC, smilni commented on assistant_dists/dream_robot_prompted/dev.yml
> +      - 8176:8176
ай блин, тут забыла сменить

2023-08-09 08:34 UTC, dilyararimovna approved these changes

2023-08-09 08:34 UTC, merged