Ru mtl2
deeppavlov/dream pull request #566
Opened 2023-09-05 14:50 UTC by dimakarp1996

2023-09-12 11:34 UTC, dilyararimovna requested changes

2023-09-12 11:34 UTC, dilyararimovna commented on assistant_dists/dream_russian/pipeline_conf.json
> +                    "endpoint": "model"
это какой-то старый формат. Поменяй на стандартный, пожалуйста

2023-09-12 11:34 UTC, dilyararimovna commented on annotators/combined_classification_ru/service_configs/combined-classification-ru/service.yml
> +      CUDA_VISIBLE_DEVICES: '0'
можно убрать отсюда

2023-09-12 11:34 UTC, dilyararimovna commented on annotators/combined_classification_ru/service_configs/combined-classification-ru/environment.yml
> +CONFIG: combined_classifier.json
_ru

2023-09-12 11:34 UTC, dilyararimovna commented on annotators/combined_classification_ru/service_configs/combined-classification-ru/service.yml
> +      CONFIG: combined_classifier.json
_ru

2023-09-14 15:05 UTC, dimakarp1996 commented on annotators/combined_classification_ru/service_configs/combined-classification-ru/service.yml
> +      CONFIG: combined_classifier.json
ok

2023-09-14 15:05 UTC, dimakarp1996 commented on annotators/combined_classification_ru/service_configs/combined-classification-ru/environment.yml
> +CONFIG: combined_classifier.json
ok

2023-09-14 15:05 UTC, dimakarp1996 commented on annotators/combined_classification_ru/service_configs/combined-classification-ru/service.yml
> +      CUDA_VISIBLE_DEVICES: '0'
ok

2023-09-14 15:05 UTC, dimakarp1996 commented on assistant_dists/dream_russian/pipeline_conf.json
> +                    "endpoint": "model"
ok

2023-09-18 07:55 UTC, dilyararimovna approved these changes

2023-09-24 06:09 UTC, dilyararimovna requested changes

2023-09-24 06:09 UTC, dilyararimovna commented on assistant_dists/dream_russian/pipeline_conf.json
> +                    "endpoint": "batch_model"
а тут почему не поменял?

2023-09-24 13:00 UTC, dimakarp1996 commented on assistant_dists/dream_russian/pipeline_conf.json
> +                    "endpoint": "batch_model"
Принято

2023-09-28 17:31 UTC, dilyararimovna requested changes

2023-09-28 17:31 UTC, dilyararimovna commented on assistant_dists/dream_russian/pipeline_conf.json
> +                    "component": "components/5eb485871be3.yml",
карточки для компоненты, не контейнера. Поэтому для этой компоненты должна быть отделньая карточка

2023-10-01 08:59 UTC, dilyararimovna requested changes

2023-10-01 08:59 UTC, dilyararimovna commented on components/5eb485871be3.yml
> +state_manager_method: add_annotation
если это карточка для аннотатора гипотез (в соответствии с пайпплайн конфом), то здесь должно быть по-другому

2023-10-03 10:31 UTC, dilyararimovna requested changes

2023-10-03 10:31 UTC, dilyararimovna commented on assistant_dists/dream_russian/pipeline_conf.json
>                      "timeout": 1.0,
в карточке таймаут 2

2023-10-03 10:31 UTC, dilyararimovna commented on assistant_dists/dream_russian/pipeline_conf.json
>                  "dialog_formatter": "state_formatters.dp_formatters:preproc_last_human_utt_dialog",
в карточке другой форматтер.

2023-10-03 10:31 UTC, dilyararimovna commented on assistant_dists/dream_russian/pipeline_conf.json
> +                "dialog_formatter": "state_formatters.dp_formatters:preproc_last_human_utt_dialog_w_hist",
а тут почему поменял? тут не должно меняться

2023-10-03 10:31 UTC, dilyararimovna commented on components/5eb485871be3.yml
> +  url: http://combined-classification-ru:8087/batch_model
неправильный порт

2023-10-10 09:34 UTC, dilyararimovna requested changes

2023-10-10 12:32 UTC, dilyararimovna approved these changes

2023-10-10 12:32 UTC, merged