User km updates
deeppavlov/dream pull request #597
Opened 2023-11-28 10:47 UTC by annakorz

User-km split into two services: user-knowledge-memorizer and user-knowledge-memorizer-prompted to be used in different distributions, dream_kg and dream_kg_prompted respectively.

2023-11-28 11:00 UTC, dilyararimovna requested changes

2023-11-28 11:00 UTC, dilyararimovna commented on assistant_dists/dream_kg/pipeline_conf.json
>                      "service": "annotators/user_knowledge_memorizer/service_configs/user-knowledge-memorizer"
-prompted

2023-11-28 11:00 UTC, dilyararimovna commented on assistant_dists/dream_kg_prompted/pipeline_conf.json
> +            "user_knowledge_memorizer_prompted": {
на самом деле вот именно это название (как и SERVICE_NAME) лучше бы оставить таким же -- потому что тогда обращение к аннотациям будет одинаковое , не зависимо от того, какой способ работает внутри.

2023-11-28 11:00 UTC, dilyararimovna commented on assistant_dists/dream_kg_prompted/pipeline_conf.json
> +            "user_knowledge_memorizer_prompted": {
то есть контейнеры разные, а вот обращение будет одинаковое `dialog["human_utterances"][-1]["annotations"]["user_knowledge_memorizer"]` -- чтобы в коде этим не заморачиваться

2023-11-28 11:00 UTC, dilyararimovna commented on components/74p4006d17yappr7ji7dtf.yml
> +name: user_knowledge_memorizer_prompted
название

2023-11-28 11:00 UTC, dilyararimovna commented on skills/dff_knowledge_prompted_skill/scenario/response.py
> +        int_ctx.get_last_human_utterance(ctx, actor).get("annotations", {}).get("user_knowledge_memorizer_prompted")
тогда тут не надо менять будет

2023-11-30 06:44 UTC, annakorz commented on assistant_dists/dream_kg_prompted/pipeline_conf.json
> +            "user_knowledge_memorizer_prompted": {
Done

2023-11-30 06:45 UTC, annakorz commented on assistant_dists/dream_kg/pipeline_conf.json
>                      "service": "annotators/user_knowledge_memorizer/service_configs/user-knowledge-memorizer"
Здесь, по-моему, все правильно: 74... это для prompted настроек, Gev... для обычного скилла.

2023-12-05 12:13 UTC, dilyararimovna approved these changes

2023-12-05 12:14 UTC, merged